<script>
$(document).ready(function () {
    'use strict';

$( "#error-dialog" ).dialog({
                        autoOpen: false,
                        show: "",
                        hide: "",
                        resizable: false,
                        modal: true,
                        buttons: {
                                Ok: function() {
                                        $( this ).dialog( "close" );
                                }
                        }
                });
});
</script>
<div id="question-container">
<?php
global $notAssessedItems, $notAnswered, $hasAnswer;
$notAssessedItems="";
$hasAnswer=0;

///echo "<hr/>";
$totAnswers = count($this->answer);

//echo "<hr/>Type: ".$this->type;

//echo "<hr/>";
//print_r($this->question);

// do not attempt to show the question if the question was not found, return an error message
if($this->type==-1)
{
	$error=true;
	echo '<p class="error-msg">The question does not exist.</p>';
} else {
	$error=false;
}

if($this->type==-2)
{
	$error=true;
	echo '<p class="error-msg">No questions have been created.</p>';
} else {
	$error=false;
}


// check if question has been answered
if (!$this->answerFirst && $this->type==1)
{
	$hasAnswer=0;
	//echo "<hr>NOT answered yet";
	$notAnswered="";
} else if ($this->answerFirst && $this->type==1) {
	$hasAnswer=1;
	//echo "<hr>Already answered";
}

/*
 * multiple view :: prevents student from seeing unpublished questions 
 */
if($this->type==0 && !$error && $_SESSION['profile']=="TEACHER")
{
	$questionsListHtml="
	<h2>Questions</h2>
<ul>";

	foreach ($this->question as $question)
	{
		$questionsListHtml.= "		
		<li><a href='/question/show?id=".$question['id']."'>".$question['name']."";
		if($question['is_published']==0)
		{
			$questionsListHtml.= " [Not Published]";
		}
	
		$questionsListHtml.= "</a></li>";
	
	}
	$questionsListHtml.="
	</ul>";
	
	echo $questionsListHtml;


} else if($this->type==1 && !$error) 

/*
 * start single view
 */
{
?>

	<!-- right-column -->
	<div id="question-right-column">
	
	<!-- start  tags-container -->
	<div id="elo-tags1" class="dashlet-box">
		<div class="dashlet-title">Tags</div>
		<div id="tags-container">
			<ul class="ul-for-data">
			<?php
			
			// prevent showing tags if question not answered
			// if ....
			$Myconcepts=getConcepts($this->question[0]['id']);
			
			//print_r($Myconcepts);
			echo analyzeTags($Myconcepts);
			
			// } end if not answered

			?>
			</ul>
		</div>

		<?php 
		if($hasAnswer==0 && $_SESSION['profile']=='STUDENT')
		{
		?>
		<!-- msg-votes-message -->
		<hr/><div class="dashlet-box-simple">Note: showing only your votes. <br/>To see all the votes you have to answer the question.</div>
		<?php } // end if ?>
	</div>
	<!-- /tags-container -->

	<?php 
	if($_SESSION['profile']=="TEACHER" && $this->question[0]['type'] == "MC")
	{
		echo '<div id="answers-graph" class="dashlet-box">
		<div class="dashlet-title">Answers</div>'
		.Answer::generateAnswersGraph($this->answer).'
		
		</div>';	
	}
	?>
	</div>
	<!-- /right-column -->

	<?php 
	/*
	<!-- debug -->
	<iframe src="" width="700px" height="500px" id="debug-votes-iframe" name="debug-votes-iframe"></iframe>	
	*/
	?>

	<!-- media container -->
	<div class="dashlet-box-image">
		<div class="dashlet-title"><?php echo $this->question[0]['name']?></div>
	<?php
		// MIKE'S CODE TO MAKE THE UPLOAD VIEW WORK //////////////////////////// 
		$mediaFile = current($this->question);
		// need the determine the media type here
		
		if (preg_match("/video/i", $mediaFile['media_type']))
		{
			echo '
		<div>
			<div id="jp_container_1" class="jp-video jp-video-270p">
                        <div class="jp-type-single">
                                <div id="jquery_jplayer_1" class="jp-jplayer"></div>
                                <div class="jp-gui">
                                        <div class="jp-video-play">
                                                <a href="javascript:;" class="jp-video-play-icon" tabindex="1">play</a>
                                        </div>
                                        <div class="jp-interface">
                                                <div class="jp-progress">
                                                        <div class="jp-seek-bar">
                                                                <div class="jp-play-bar"></div>
                                                        </div>
                                                </div>
                                                <div class="jp-current-time"></div>
                                                <div class="jp-duration"></div>
                                                <div class="jp-title">
                                                        <ul>
                                                                <li>' . $mediaFile['name'] . '</li>
                                                        </ul>
                                                </div>
                                                <div class="jp-controls-holder">
                                                        <ul class="jp-controls">
                                                                <li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
                                                                <li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
                                                                <li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
                                                                <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
                                                                <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
                                                                <li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
                                                        </ul>
                                                        <div class="jp-volume-bar">
                                                                <div class="jp-volume-bar-value"></div>
                                                        </div>

                                                        <ul class="jp-toggles">
                                                                <li><a href="javascript:;" class="jp-full-screen" tabindex="1" title="full screen">full screen</a></li>
                                                                <li><a href="javascript:;" class="jp-restore-screen" tabindex="1" title="restore screen">restore screen</a></li>
                                                                <li><a href="javascript:;" class="jp-repeat" tabindex="1" title="repeat">repeat</a></li>
                                                                <li><a href="javascript:;" class="jp-repeat-off" tabindex="1" title="repeat off">repeat off</a></li>
                                                        </ul>
                                                </div>
                                        </div>
                                </div>
                                <div class="jp-no-solution">
                                        <span>Update Required</span>
                                        To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
                                </div>
                        </div>

                </div>
	</div>
		<script>
			$("#jquery_jplayer_1").jPlayer({
                                        ready: function() { // The $.jPlayer.event.ready event
                                           $(this).jPlayer("setMedia", { m4v: "' . $mediaFile['media_content'] .  '" }); //.jPlayer("play");
                                        },
                                        ended: function() { // The $.jPlayer.event.ended event
                                            //$(this).jPlayer("play"); // Repeat the media
                                        },
                                        size: {
                                                            width: "460px",
                                                            height: "270px",
                                                            cssClass: "jp-video-270p"
                                                    },

                                     solution:"html, flash",
                                     swfPath: "/jquery/jplayer",
                                     supplied: "m4v",
                                     errorAlerts: true
                                    });
		</script>
			';
			echo "<br/>";
			
		} else { 

			echo '
			<div class="image-holder">
				<img src="'.$mediaFile['media_content'].'" alt="'.$this->question[0]['name'].'" width="600px" />
			</div>';
		}
		//<img  height="240px" title="Drag and Drop a new Media File here..." alt="Drag and Drop a new Media File here..." src="/images/uploader.png" id="eloimg">
		?>	
	</div> 
	<!-- /media container -->

	<div id="question-content">
	<?php 
		echo $this->question[0]['content'];
	?>
	</div>
	
	<?php 
	// update status 
	if($_SESSION["profile"]=="TEACHER" && $this->question[0]['is_published']==0)
	{
	?>
	<div id="updatestatus-container">
		<form method="post" action="/question/updatestatus">
			<input type="hidden" id="question_id"  name="question_id" value="<?php echo $this->question[0]['id']?>"/>
			<div>
				<span class="item-label">Name: </span>
				<span class="item-input"><input type="text" name="name" value = "<?php echo $this->question[0]['name']?>"/></span> 
			</div>
			<div>
			<span class="item-label">Published: </span>
			<span class="item-input">
				<select name="is_published">
					<option value="1"<?php if($this->question[0]['is_published']==1) { echo "selected"; }?>>Yes</option>
					<option value="0"<?php if($this->question[0]['is_published']==0) { echo "selected"; }?>>No</option>
				</select>
			</span>
			</div>

			<div>
			<span class="item-label">Allow Multiple Answers: </span>
			<span class="item-input">
				<select name="allow_multipe_answer">
					<option value="1"<?php if($this->question[0]['allow_multipe_answer']==1) { echo "selected"; }?>>Yes</option>
					<option value="0"<?php if($this->question[0]['allow_multipe_answer']==0) { echo "selected"; }?>>No</option>
				</select>
			</span>
			</div>

			<div>
			<br/>
			<textarea cols="25" name="content"><?php echo $this->question[0]['content'];?></textarea>
			</div>
			<br/>
			<?php
			/* 
			<span class="item-label">Published: </span>
			<span class="item-input">
				<select name="is_public">
					<option value="1"<?php if($this->question[0]['is_public']==1) { echo "selected"; }?>>Yes</option>
					<option value="0"<?php if($this->question[0]['is_public']==0) { echo "selected"; }?>>No</option>
				</select>
			 </span>
			 */
			 ?>
			 <input type="submit" value="Update Question">
		</form>
		<br/>
	</div>
	<?php
	} // end if teacher && question not published
	?>
	
<!-- 
	<div class="clear"></div>
-->

	<?php 
	$answerIsEmptyMsg="";
	
	if($_SESSION["profile"]=="TEACHER")
	{
		$answerTitle = '<div class="dashlet-title">Answers</div>';
		if($totAnswers==0)
		{
			$answerIsEmptyMsg = '<div class="no-results">There are no answers</div>';	
		}
		
	} else if($_SESSION["profile"]=="STUDENT") {
		$answerTitle = 'My Answer';
	}
	?>

	<?php
	if($_SESSION["profile"]=="TEACHER" && isset($this->assessmentReview))
	{
	?>
		<div id='assessment-notes-container'>
		<b>My Notes:</b> <?php echo $this->assessmentReview; ?>
		</div>
	<?php
	}
	?>
	<!-- answers-container -->
	<div id="answers-container">

		<!-- /assessment answer form -->
		<form name="assessment-form" method="post" action="/assessment/add?prefix=assessAnsw_">

	<?php
	//loop through the answers
	$answersHtml="";
	foreach ($this->answer as $answer)
	{
		// check if it is my answer(s)
		if($_SESSION['author_id']==$answer['author_id'])
		{
			$myAnswerCss="my-answer";
			$isMy=true;
		} else {
			$myAnswerCss="";
			$isMy=false;
		}

	// start answer item
	$answersHtml.='
	<div id="answer' . $answer['id'] . '" class="answer-item '.$myAnswerCss.'">
		';

		// answer MC
		if($this->question[0]['type'] == "MC" )
		{
			$answersHtml.= '<div class="answer-mc">'.$answer['mc_chocie'].'</div>';
		}
	
		// assesment form or grade if not graded
		if($_SESSION["profile"]=="TEACHER" || $isMy)
		{
			$answersHtml  .=''.checkHasAssessment($answer['author_id'], $answer['id'], 2); // obj_type = 2 answers in assessable
		} 
		// content
		if(isset($this->answer[0]['content']))
		{
			$answersHtml.='<div class="answer-content">'.$answer['content'].'</div>'; 
		}
		
		// user name
		$answersHtml .='
		<div class="answer-user_name">
			<span>Answered by:</span>
			<a href="#">'.getUserName($answer['author_id']).'</a>  <div class="date">'.$answer['date_created'].'</div>
		</div>';
		
	// end answer item
	$answersHtml.='
	</div>
		';

	} // end loop answers	

	echo $answersHtml;
	?>
	<?php
	// controls for submiting marks 
	if($_SESSION['profile']=="TEACHER" && $this->question[0]['is_published']==1)
	{
	?>
		<input type="hidden" value="2" name="obj_type"> <!-- 2=answer-->
		<input type="hidden" value="<?php echo $this->question[0]['id']; ?>" name="parent_id">
		<input type="hidden" value="question" name="parent_type">
		<input type="hidden" value="<?php echo $notAssessedItems; ?>" name="assesment_list">
		<input type="hidden" value="10" name="assessAnsw_activity_type_id">
		<input type="hidden" name="assessAnsw_s1" value="Question" >
		<input type="hidden" name="assessAnsw_s2" value="Answer" >
		<input type="hidden" name="assessAnsw_s3" value="Assessment" >
		<input type="hidden" name="assessAnsw_t1" value="Assessment on Answer" >
<?php 
// show "Submit Marks" button only if there are answers to be assessed 
if($notAssessedItems!="")
{
?>        	        			
		<div id="btn_submit_marks" class="div-show">
			<input id="btn_submit_marks" type="button" value="Submit Marks" onclick="showAssessmentReview()">
		</div>
<?php 
} // end if there are answers to be assessed
?>
		<div id="assessment-review-container" class="dashlet-box div-hide">
			<div class="dashlet-title">Assessment Review</div>
			<textarea name="review-log" rows="" cols="" name="assessment_review"></textarea>
			<br/>
			<input type='checkbox' value='true' name='markForDiscussion' /> Mark for Discussion
			<br/>
			<br/>
			<input type="submit" value="Confirm">
			<input type="button" value="Cancel" onclick="marksCancel()">
		</div>
<?php 
	} // end if teacher
?>
	</form>
	<!-- /assessment answer form -->
</div>
<!-- /answers-container -->
	<div id="error-dialog" title="Submission Error">
               <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
               <span id="error-dialogue-text"></span>
    </div>

	<?php 
	// need to change this: need to look if question can be resubmitted.
	// check if question is published as well
	//if(($_SESSION["profile"]=="STUDENT" && $this->question[0]['allow_multipe_answer']==1) || ($_SESSION["profile"]=="STUDENT" && !isset($this->answer[0])))
	//if($_SESSION["profile"]=="STUDENT" && !isset($this->answer[0]))
	if(($_SESSION["profile"]=="STUDENT" && $this->question[0]['allow_multipe_answer']==1) || 
	($_SESSION["profile"]=="STUDENT" && !isset($this->answer[0])))
	{
		// show message for re-answering
		if ($this->question[0]['allow_multipe_answer']==1 && $hasAnswer)
		{
			echo '<div class="msg-reanswer">'.$this->PLACEWEB_CONFIG['reAnswerPrompt'].'</div>';
		}
	?>
	<!-- submit answer form -->
	<div id="answer-question-container">
		<form method="post" id="saveAnswerForm" action="/question/addanswer?prefix=answ_">
		<?php 
			// add here the posible answers when the elo is a multiple choice
			///*
			if($this->question[0]['type'] == "MC" )
			{
				$anwersFormHtml = '
				<div id="answers-container" style="width:30%; " class="dashlet-box-simple">
				<div class="dashlet-title">Multiple Choice</div>
				';
				for($k=1;$k<=$this->question[0]['choices'];$k++)
				{
					$anwersFormHtml .= ' '.$this->PLACEWEB_CONFIG['questionChoices'][$k].'<input type="radio" name="mc_chocie" value="'.$this->PLACEWEB_CONFIG['questionChoices'][$k].'"/>&nbsp;&nbsp;';	
				}
				$anwersFormHtml .= '
				
				</div>
				';
				echo $anwersFormHtml;
			}
			//*/
			?>
		<div  class="dashlet-box html-editor" style="float:left;">
			<div class="dashlet-title"><?php echo $answerTitle ?></div>
	

			<input type="hidden" id="question_id"  name="question_id" value="<?php echo $this->question[0]['id']?>"/>
			<textarea name="content"></textarea>
			<br/><input type="button" onClick="saveAnswer()" value="Save Answer">
			</div>
		</form>
	</div>
		<!-- /submit answer form -->
	
	<?php 	
	} // end if student
	?>
	<?php // target="debug-votes-iframe"?>
	<!--  start add vote on question_concept -->
	<form id="qe_vote_form" method="post" action="/votes/add?prefix=qe_">
		<input type="hidden" name="qe_obj_id" id="qe_obj_id" value=""/>
		<input type="hidden" name="qe_obj_type" id="qe_obj_type" value="5"/>
		<input type="hidden" name="qe_vote_value" id="qe_vote_value" value=""/>
		<input type="hidden" name="qe_activity_type_id" id="qe_activity_type_id" value="14"/>
		<input type="hidden" name="qe_activity_on_user" id="qe_activity_on_user" value=""/>
		<input type="hidden" name="qe_i1" id="qe_i1" value="<?php echo $this->question[0]['id']; ?>"/>
		<input type="hidden" name="qe_i2" id="qe_i2" value=""/>
		<input type="hidden" name="qe_s1" id="qe_s1" value="Question"/>
		<input type="hidden" name="qe_s2" id="qe_s2" value="QuestionConcept"/>
		<input type="hidden" name="qe_t1" id="qe_t1" value="Voted on QuestionConcept"/>
		<input type="hidden" name="hasAnswer" id="hasAnswer" value="<?php echo $hasAnswer;?>"/>
		
	</form>
	<!--  end add vote to example_concept -->
	
	<!--  start add question_concept -->
	<form id="qe_tag_form" method="post" action="/tags/add?prefix=taggqe_">
	<input type="hidden" name="qe_id" id="qe_id" value="<?php echo $this->question[0]['id']; ?>"/>
	<input type="hidden" name="concept_id" id="concept_id" value=""/>
	<input type="hidden" name="tag_type" id="tag_type" value="2"/> <?php // 1 for example, 2 for questions?>
	
	<input type="hidden" name="taggqe_activity_type_id" id="taggqe_activity_type_id" value="16"/>
	<input type="hidden" name="taggqe_activity_on_user" id="taggqe_activity_on_user" value=""/>
	<input type="hidden" name="taggqe_s1" id="taggqe_s1" value="Question"/>
	<input type="hidden" name="taggqe_s2" id="taggqe_s2" value="Concept"/>
	<input type="hidden" name="taggqe_s3" id="taggqe_s3" value="QuestionConcept"/>
	<input type="hidden" name="taggqe_t1" id="taggqe_t1" value="Tagg Question with a Concept"/>
		
	
<?php 
/**
 * we need new types of activity for this
 */
?>
<!-- 
		<input type="hidden" name="ex_activity_type_id" id="ex_activity_type_id" value=""/> 
		<input type="hidden" name="ex_activity_on_user" id="ex_activity_on_user" value=""/> 
	
		<input type="hidden" name="ex_i1" id="ex_i1" value="<?php //echo $this->example[0]['id']; ?>"/>
		<input type="hidden" name="ex_i2" id="ex_i2" value=""/>
		<input type="hidden" name="ex_t1" id="ex_t1" value="Example"/>
		<input type="hidden" name="ex_t2" id="ex_t2" value="ExampleConcept"/>
-->
	</form>
	<!--  end add question_concept -->
	
<?php 	
} // end single view
?>


</div><!-- /question-container -->


<?php 

function checkHasAssessment($author_id, $obj_id, $obj_type)
{
	global $notAssessedItems;

	// checked ok!
	$q = Doctrine_Query::create()
	->select('a.id, a.mark')
	->from('Assessment a')
	->where('a.run_id = ? AND a.obj_id = ? AND a.obj_type = ?', 
		array($_SESSION['run_id'], $obj_id, $obj_type));

	$assessment = $q->fetchArray();
	//echo '<hr>';
	//echo print_r($assessment);
	
	if(count($assessment)==0)
	{
		// add this iterm to the assessment list
		$notAssessedItems .= "".$obj_id.",";
		//return "has no assessment";
		//echo "<hr>checkHasAssessment: ".$notAssessedItems;
		if($_SESSION['profile']=="TEACHER")
		{
			return renderAssessmentFormItem($obj_id,$author_id);
			//$author_id
		} else {
			return "";
		}
		
	} else {
		return '<div class="assessment-mark">'.$assessment[0]['mark'].'</div>';
		
	}
	
	//return $assessment;
}

function renderAssessmentFormItem($id,$author_id)
{
	$assessmentForm = '
	<div class="assessment-item">
			<input type="radio" value="1" name="mark_'.$id.'">1  |
			<input type="radio" value="2" name="mark_'.$id.'">2  |
			<input type="radio" value="3" name="mark_'.$id.'">3  |
			<input type="radio" value="4" name="mark_'.$id.'">4   
			<input type="hidden" value="'.$id.'" name="obj_id_'.$id.'">
			<input type="hidden" value="'.$author_id.'" name="author_id_'.$id.'">
	</div>
	';
	return $assessmentForm;
}

function getUserName($author_id)
{
	$q = Doctrine_Query::create()
	->select('u.display_name')	
	->from('User u')
	->where('u.id = ?', $author_id);
	 
	$user = $q->fetchArray();
	
	//print_r($user);
	return $user[0]['display_name'];
	
}

function getConcepts($id)
{
	$q = Doctrine_Query::create()
	->select('e.id, e.question_id,  e.concept_id')
	->from('QuestionConcept e')
	->where('e.question_id = ? AND e.run_id = ?', array($id,$_SESSION['run_id']));
	 
	$result = $q->fetchArray();

	return $result;
}

function countVotes($obj_id, $obj_type)
{
	global $hasAnswer;
	
	// prevent showing other's votes when question has not been answered
	if($hasAnswer==0 && $_SESSION['profile']=="STUDENT")
	{
		//echo "<hr>showing only my votes";
		// get only active users' votes for this post 
		// ****************************************** 
	    $q = Doctrine_Query::create()
		->select ("v.id, v.vote_value")
		->from("Vote v")
		->where('v.run_id = ? AND v.obj_id = ? AND v.obj_type = ? AND v.author_id = ?' , 
		array($_SESSION['run_id'],$obj_id, $obj_type, $_SESSION['author_id'])) 				
		->orderBy('v.id DESC');
	} else {
		//echo "<hr>showing all the votes";
	
		// get all votes for this post 
		// ***************************** 
	    $q = Doctrine_Query::create()
		//->select ("v.id, v.vote_value, u.id, u.username") // use this if we want to show who and how someone voted
		->select ("v.id, v.vote_value")
		->from("Vote v")
		//->innerJoin("v.User u")
		->where('v.run_id = ? AND v.obj_id = ? AND v.obj_type = ?' , 
		array($_SESSION['run_id'],$obj_id, $obj_type)) 				
		->orderBy('v.id DESC');
	}
	
	$votes = $q->fetchArray();

	$votesCount = array();
	$votesSumm = 0; $votesMinus = 0; $votesPlus = 0;
	
	foreach ($votes as $vote)
	{
		$votesSumm += $vote['vote_value'];
		
		if($vote['vote_value']==-1)
		{
			$votesMinus-= $vote['vote_value'];
		} else {
			$votesPlus+= $vote['vote_value'];
		}
		
	}
	$votesCount = array (
		"votesSumm" => $votesSumm,
		"votesMinus" => $votesMinus,
		"votesPlus" => $votesPlus
	);
	return $votesCount;
	// end get votes
	
} // end countVotes()

function analyzeTags($tags, $prefix="")
{
	
	$prefix = "qe_"; // same for voting on question_concept and example_concept
	//get all Concepts in db for comparison: which ones are not added yet
	$q = Doctrine_Query::create()
		->select('e.id,  e.name')
		->from('Concept e')
		->where('e.run_id = ?', $_SESSION['run_id']);
	
	$theConcepts = $q->fetchArray();
	
	//$theConcepts=Doctrine::getTable("Concepts")->findAll(Doctrine::HYDRATE_ARRAY);
	
	//print_r($theConcepts);
	//print_r($tags);
	
	$currentConcepts = array(); // collects the concepts already associated to the example
	//$notIncludedConcepts = array();
	$theConceptsF = array(); // formats the concepts in db to same structure than current $currentConcepts

	//$PLACEWEB_CONFIG['fConcepts']
	
	$tagsHtml = "";
	$notIncludedConceptsHtml = "";
	
	$whoHasVoted = array();
	$conn=0;
	
	// adjust the concepts from db 
	foreach($theConcepts as $concept)
	{
		$theConceptsF[$concept['id']] = $concept['name'];
	}
	
	//print_r($theConceptsF);
	
	foreach ($tags as $tag)
	{
		/* 
		 * get votes data
		 */ 

			// collect tags for comparison 
			$currentConcepts[$tag['concept_id']] = $theConceptsF[$tag['concept_id']];
			
		
		//var_dump($tag);
		//echo "<br/>".$tag['conceptId'];
		
			$votesCount = countVotes($tag['id'], 5); // look for votes for obj_type = 5 question_concept
		
		$tagsHtml .='
		<li>
			<div class="tag-name">'.$theConceptsF[$tag['concept_id']].'</div>
			<div class="votes-container" style="float:right;">
				<div  id="'.$prefix.'vote-loading-'.$tag['id'].'"></div> 
				<div  id="'.$prefix.'vote-minus-'.$tag['id'].'" class="vote-minus-plus">
					'.$votesCount['votesMinus'].'
				</div> 
				<div class="vote-icon">
					<a href="javascript:postVote(-1,'.$tag['id'].',5,'.$_SESSION['author_id'].',\''.$prefix.'\');"><img src="/images/icon_arrow_down.png" width="12px"></a>
				</div>
				<div  id="'.$prefix.'vote-total-'.$tag['id'].'" class="vote-total">
					'.$votesCount['votesSumm'].'
				</div>
				<div class="vote-icon">
					<a href="javascript:postVote(1,'.$tag['id'].',5,'.$_SESSION['author_id'].',\''.$prefix.'\');"><img src="/images/icon_arrow_up.png" width="12px"></a>
				</div>
				<div  id="'.$prefix.'vote-plus-'.$tag['id'].'" class="vote-minus-plus">
					'.$votesCount['votesPlus'].'
				</div> 
			</div>
		</li>';
			
			$conn++;
	}
	
	$notIncludedConcepts = array_diff($theConceptsF, $currentConcepts);

	//print_r($currentConcepts);
	//print_r($notIncludedConcepts);
	
	// not included tags
	foreach ($notIncludedConcepts as $diffTagId => $diffTagVal)
	{
		$notIncludedConceptsHtml .='
		<li>
			<div class="tag-name">'.$diffTagVal.'</div>
			<div class="tag-add"><a href="javascript:addTag(\''.$diffTagId.'\');">[Add]</a></div>
		</li>';
		
		//echo "<br/>".$diffTagId;
	} 
	
	return $tagsHtml.$notIncludedConceptsHtml;

} // end fnc
?>
