<div id="question-container">
<?php
///echo "<hr/>";
$totAnswers = count($this->answer);

//echo "<hr/>Type: ".$this->type;

//echo "<hr/>";
//print_r($this->question);

// do not attempt to show the question if the question was not found, return an error message
if($this->type==-1)
{
	$error=true;
	echo '<p class="error-msg">The question does not exist.</p>';
} else {
	$error=false;
}

if($this->type==-2)
{
	$error=true;
	echo '<p class="error-msg">No questions have been created.</p>';
} else {
	$error=false;
}

/*
 * multiple view
 */
if($this->type==0 && !$error)
{
	$questionsListHtml="
	<h2>Questions</h2>
<ul>";

	foreach ($this->question as $question)
	{
		$questionsListHtml.= "		
		<li><a href='/question/show?id=".$question['id']."'>".$question['name']."</a></li>";
	}
	$questionsListHtml.="
	</ul>";
	
	echo $questionsListHtml;


} else if($this->type==1 && !$error) 

/*
 * start single view
 */
{
?>
<h3><?php echo $this->question[0]['name']?></h3>

	<?php 
	// update status 
	if($_SESSION["profile"]=="TEACHER")
	{
	?>
	<div id="updatestatus-container">
		<form method="post" action="/question/updatestatus">
			<input type="hidden" id="question_id"  name="question_id" value="<?php echo $this->question[0]['id']?>"/>
			<span class="item-label">Status: </span>
			<span class="item-input">
				<select name="status">
					<option value="1"<?php if($this->question[0]['status']==1) { echo "selected"; }?>>Active</option>
					<option value="0"<?php if($this->question[0]['status']==0) { echo "selected"; }?>>Inactive</option>
				</select>
			</span> 
		 <input type="submit" value="Update status">
		</form>
		<br/>
	</div>
	<?php
	} // 
	?>
	
	<div class="dashlet-box-image">
		<div><?php echo $this->question[0]['media_content'];?></div>
	</div>
	<div><?php echo $this->question[0]['content'];?></div>

	<!-- start  tags-container -->
	<div id="elo-tags" class="dashlet-box" style="width:30%; float:right;">

		<div class="dashlet-title">Tags</div>

		
		<div id="tags-container">
		<?php //print_r($myContentArray[0]['tags']);?>
			<ul class="ul-for-data">
			<?php
			$Myconcepts=getConcepts($this->question[0]['id']);
			
			//print_r($Myconcepts);
			echo __analyzeTags($Myconcepts);

			?>
			</ul>
		</div>
	</div>
	<!-- /tags-container -->	
	
	<?php 
	if($_SESSION["profile"]=="TEACHER")
	{
		echo "<h3>Answers</h3>";
		if($totAnswers==0)
		{
			echo "<p>There are no answers</p>";	
		}
		
	} else if($_SESSION["profile"]=="STUDENT") {
		echo "<h3>My Answer</h3>";
	}
	?>
	
	<?php
	//loop through the answers
	$answersHtml="";
	foreach ($this->answer as $answer)
	{
		$answersHtml.='
		<div class="answer-item">
		';
		// assesment form
		if($_SESSION["profile"]=="TEACHER")
		{
			// check if the answer has an assessment
			
			$answersHtml.='<div id="answer_'.$answer['id'].'" class="answer-assessment">
			<form action="/assessment/add" method="post">
			1 <input type="radio" name="mark_'.$answer['id'].'" value="1"/> |
			2 <input type="radio" name="mark_'.$answer['id'].'" value="2"/> |
			3 <input type="radio" name="mark_'.$answer['id'].'" value="3"/> |
			4 <input type="radio" name="mark_'.$answer['id'].'" value="4"/>  
			<input type="hidden" name="answer_id" value="'.$answer['id'].'">
			<input type="hidden" name="obj_type" value="2">
			<input type="submit" value="Save Assessment">
			</form>
			</div>';
		} 

		// content
		if(isset($this->answer[0]['content']))
		{
			$answersHtml.='<div class="answer-content">'.$answer['content'].'</div>'; 
		}
		// answer
		if($this->question[0]['type'] == "MC" )
		{
			$answersHtml.= '<div class="answer-mc">Multiple Choice: '.$answer['mc_chocie'].'</div>';
		}
		
		// user name
		$answersHtml .='<div class="answer-username">'.getUserName($answer['author_id']).'</div>';
		
		$answersHtml.='
		</div>
		';
	} // end loop answers	
	
	echo $answersHtml;
	
	if($_SESSION["profile"]=="STUDENT" && !isset($this->answer[0]))
	{
	?>
	<p></p>
	<form method="post" action="/question/addanswer">
		<input type="hidden" id="question_id"  name="question_id" value="<?php echo $this->question[0]['id']?>"/>
		<?php 
		// add here the posible answers when the elo is a multiple choice
		///*
		if($this->question[0]['type'] == "MC" )
		{
			$anwersFormHtml = '
			<div id="answers-container" style="width:30%; " class="dashlet-box-simple">
			<div class="dashlet-title">Multiple Choice</div>
			';
			for($k=1;$k<=$this->question[0]['choices'];$k++)
			{
				$anwersFormHtml .= ' '.$this->PLACEWEB_CONFIG['questionChoices'][$k].'<input type="radio" name="mc_chocie" value="'.$this->PLACEWEB_CONFIG['questionChoices'][$k].'"/>&nbsp;&nbsp;';	
			}
			$anwersFormHtml .= '
			
			</div>
			';
			echo $anwersFormHtml;
		}
		//*/
		?>
		<textarea name="content"></textarea>
		<br/><input type="submit" value="Save Answer"> 
	</form>
	
	<?php 	
	} // 
	?>


<?php 	
} // end single view
?>


</div><!-- /question-container -->


<?php 
function getUserName($author_id)
{
	$q = Doctrine_Query::create()
	->select('u.username')	
	->from('User u')
	->where('u.id = ?', $author_id);
	 
	$user = $q->fetchArray();
	
	//print_r($user);
	return $user[0]['username'];
	
}

function getConcepts($id)
{
	$q = Doctrine_Query::create()
	->select('e.question_id,  e.concept_id')
	->from('QuestionConcept e')
	->where('e.question_id = ? AND e.run_id = ?', array($id,$_SESSION['run_id']));
	 
	$result = $q->fetchArray();

	return $result;
}

	function __analyzeTags($tags)
	{

		//get Concepts
		$q = Doctrine_Query::create()
			->select('e.id,  e.name')
			->from('Concept e')
			->where('e.run_id = ?', $_SESSION['run_id']);
		
		$theConcepts = $q->fetchArray();
		
		//print_r($theConcepts);
		//print_r($tags);
		
		$currentTags = array();
		//$diffTags = array();
		$theConceptsF = array();
		//$PLACEWEB_CONFIG['fConcepts']
		
		$tagsHtml = "";
		$diffTagsHtml = "";
		
		$whoHasVoted = array();
		$conn=0;
		
		foreach($theConcepts as $concept)
		{
			$theConceptsF[$concept['id']] = $concept['name'];
		}
		
		//print_r($theConceptsF);
		
		foreach ($tags as $tag)
		{
			// sum votes for each tag
			$votes=0;
			/*
			foreach ($tag['votes'] as $vote)
			{
				$votes+=$vote['vote'];
				// collect how has voted  
				$whoHasVoted[]=$vote['author'];
			}
			*/

				// collect tags for comparison 
				$currentTags[$tag['concept_id']] = $theConceptsF[$tag['concept_id']];
				
			
			//var_dump($tag);
			//echo "<br/>".$tag['conceptId'];

				/*
				$tagsHtml .='
			<li>

			</li>
				';
				*/
				
				
			$tagsHtml .='
			<li>
				<div class="tag-name">'.$theConceptsF[$tag['concept_id']].'</div>
				<div class"vote-icons">
					<a href="javascript:tagVote(1,'.$tag['concept_id'].')"><img src="/images/vote_like.png" width="20px"></a>
					<a href="javascript:tagVote(-1,'.$tag['concept_id'].')"><img src="/images/vote_dislike.png" width="20px"></a>
				</div> 
				<div class="tag-votes">'.$votes.'</div>
			</li>';
			
				
				$conn++;
		}
		
		$diffTags = array_diff($theConceptsF, $currentTags);

		//print_r($currentTags);
		//print_r($diffTags);
		
		$diffTagsHtml = "
		<li> &nbsp; 
		</li>
		";
		
		// not included tags
		foreach ($diffTags as $diffTagId => $diffTagVal)
		{
			$diffTagsHtml .='
			<li>
				<div class="tag-name">'.$diffTagVal.'</div>
				<div class="tag-add"><a href="javascript:addTag(\''.$diffTagId.'\');">[Add]</a></div>
			</li>';
			
			//echo "<br/>".$diffTagId;
		} 
		
		return $tagsHtml.$diffTagsHtml;

	} // end fnc


?>