<div id="question-container">
<?php
///echo "<hr/>";
$totAnswers = count($this->answer);

//echo "<hr/>Type: ".$this->type;

//echo "<hr/>";
//print_r($this->question);

// do not attempt to show the question if the question was not found, return an error message
if($this->type==-1)
{
	$error=true;
	echo '<p class="error-msg">The question does not exist.</p>';
} else {
	$error=false;
}

if($this->type==-2)
{
	$error=true;
	echo '<p class="error-msg">No questions have been created.</p>';
} else {
	$error=false;
}

/*
 * multiple view
 */
if($this->type==0 && !$error)
{
	$questionsListHtml="
	<h2>Questions</h2>
<ul>";

	foreach ($this->question as $question)
	{
		$questionsListHtml.= "		
		<li><a href='/question/show?id=".$question['id']."'>".$question['name']."</a></li>";
	}
	$questionsListHtml.="
	</ul>";
	
	echo $questionsListHtml;


} else if($this->type==1 && !$error) 

/*
 * start single view
 */
{
?>
<h3><?php echo $this->question[0]['name']?></h3>

	<!-- start  tags-container -->
	<div id="elo-tags" class="dashlet-box" style="width:30%; float:right;">
		<div class="dashlet-title">Tags</div>
		<div id="tags-container">
		<?php //print_r($myContentArray[0]['tags']);?>
			<ul class="ul-for-data">
			<?php
			$Myconcepts=getConcepts($this->question[0]['id']);
			
			//print_r($Myconcepts);
			echo analyzeTags($Myconcepts);

			?>
			</ul>
		</div>
	</div>
	<!-- /tags-container -->
	
	<?php 
	// update status 
	if($_SESSION["profile"]=="TEACHER")
	{
	?>
	<div id="updatestatus-container">
		<form method="post" action="/question/updatestatus">
			<input type="hidden" id="question_id"  name="question_id" value="<?php echo $this->question[0]['id']?>"/>
			<span class="item-label">Status: </span>
			<span class="item-input">
				<select name="status">
					<option value="1"<?php if($this->question[0]['status']==1) { echo "selected"; }?>>Active</option>
					<option value="0"<?php if($this->question[0]['status']==0) { echo "selected"; }?>>Inactive</option>
				</select>
			</span> 
		 <input type="submit" value="Update status">
		</form>
		<br/>
	</div>
	<?php
	} // 
	?>
	
	<div class="dashlet-box-image">
		<div><?php 
			echo '<img src="/content/'.$this->question[0]['media_path'].'" title="'.$this->question[0]['name'].'" width="320px" />';
		//echo $this->question[0]['media_content'];?></div>
	</div>
	<div><?php 
		echo $this->question[0]['content'];?>
		</div>

	
	<?php 
	if($_SESSION["profile"]=="TEACHER")
	{
		echo "<h3>Answers</h3>";
		if($totAnswers==0)
		{
			echo "<p>There are no answers</p>";	
		}
		
	} else if($_SESSION["profile"]=="STUDENT") {
		echo "<h3>My Answer</h3>";
	}
	?>
	
	<?php
	//loop through the answers
	$answersHtml="";
	foreach ($this->answer as $answer)
	{
		$answersHtml.='
		<div class="answer-item">
		';
		// assesment form
		if($_SESSION["profile"]=="TEACHER")
		{
			// check if the answer has an assessment
			
			$answersHtml.='<div id="answer_'.$answer['id'].'" class="answer-assessment">
			<form action="/assessment/add" method="post">
			1 <input type="radio" name="mark_'.$answer['id'].'" value="1"/> |
			2 <input type="radio" name="mark_'.$answer['id'].'" value="2"/> |
			3 <input type="radio" name="mark_'.$answer['id'].'" value="3"/> |
			4 <input type="radio" name="mark_'.$answer['id'].'" value="4"/>  
			<input type="hidden" name="answer_id" value="'.$answer['id'].'">
			<input type="hidden" name="obj_type" value="2">
			<input type="submit" value="Save Assessment">
			</form>
			</div>';
		} 

		// content
		if(isset($this->answer[0]['content']))
		{
			$answersHtml.='<div class="answer-content">'.$answer['content'].'</div>'; 
		}
		// answer
		if($this->question[0]['type'] == "MC" )
		{
			$answersHtml.= '<div class="answer-mc">Multiple Choice: '.$answer['mc_chocie'].'</div>';
		}
		
		// user name
		$answersHtml .='<div class="answer-username">'.getUserName($answer['author_id']).'</div>';
		
		$answersHtml.='
		</div>
		';
	} // end loop answers	
	
	echo $answersHtml;
	
	if($_SESSION["profile"]=="STUDENT" && !isset($this->answer[0]))
	{
	?>
	<p></p>
	<form method="post" action="/question/addanswer">
		<input type="hidden" id="question_id"  name="question_id" value="<?php echo $this->question[0]['id']?>"/>
		<?php 
		// add here the posible answers when the elo is a multiple choice
		///*
		if($this->question[0]['type'] == "MC" )
		{
			$anwersFormHtml = '
			<div id="answers-container" style="width:30%; " class="dashlet-box-simple">
			<div class="dashlet-title">Multiple Choice</div>
			';
			for($k=1;$k<=$this->question[0]['choices'];$k++)
			{
				$anwersFormHtml .= ' '.$this->PLACEWEB_CONFIG['questionChoices'][$k].'<input type="radio" name="mc_chocie" value="'.$this->PLACEWEB_CONFIG['questionChoices'][$k].'"/>&nbsp;&nbsp;';	
			}
			$anwersFormHtml .= '
			
			</div>
			';
			echo $anwersFormHtml;
		}
		//*/
		?>
		<textarea name="content"></textarea>
		<br/><input type="submit" value="Save Answer"> 
	</form>
	
	<?php 	
	} // end if student
	?>

	<!--  start add vote on question_concept -->
	<form id="qe_vote_form" method="post" action="/votes/add?prefix=qe_">
		<input type="hidden" name="qe_obj_id" id="qe_obj_id" value=""/>
		<input type="hidden" name="qe_obj_type" id="qe_obj_type" value="5"/>
		<input type="hidden" name="qe_vote_value" id="qe_vote_value" value=""/>
		<input type="hidden" name="qe_activity_type_id" id="qe_activity_type_id" value="14"/>
		<input type="hidden" name="qe_activity_on_user" id="qe_activity_on_user" value=""/>
		<input type="text" name="qe_i1" id="qe_i1" value="<?php echo $this->question[0]['id']; ?>"/>
		<input type="hidden" name="qe_i2" id="qe_i2" value=""/>
		<input type="hidden" name="qe_t1" id="qe_t1" value="Question"/>
		<input type="hidden" name="qe_t2" id="qe_t2" value="QuestionConcept"/>
	</form>
	<!--  end add vote to example_concept -->
	
	<!--  start add question_concept -->
	<form id="qe_tag_form" method="post" action="/tags/add?prefix=qe_">
	<input type="hidden" name="qe_id" id="qe_id" value="<?php echo $this->question[0]['id']; ?>"/>
	<input type="hidden" name="concept_id" id="concept_id" value=""/>
	<input type="hidden" name="tag_type" id="tag_type" value="2"/> <?php // 1 for example, 2 for questions?>
	
<?php 
/**
 * we need new types of activity for this
 */
?>
<!-- 
		<input type="hidden" name="ex_activity_type_id" id="ex_activity_type_id" value=""/> 
		<input type="hidden" name="ex_activity_on_user" id="ex_activity_on_user" value=""/> 
	
		<input type="hidden" name="ex_i1" id="ex_i1" value="<?php //echo $this->example[0]['id']; ?>"/>
		<input type="hidden" name="ex_i2" id="ex_i2" value=""/>
		<input type="hidden" name="ex_t1" id="ex_t1" value="Example"/>
		<input type="hidden" name="ex_t2" id="ex_t2" value="ExampleConcept"/>
-->
	</form>
	<!--  end add question_concept -->
	
<?php 	
} // end single view
?>


</div><!-- /question-container -->


<?php 
function getUserName($author_id)
{
	$q = Doctrine_Query::create()
	->select('u.username')	
	->from('User u')
	->where('u.id = ?', $author_id);
	 
	$user = $q->fetchArray();
	
	//print_r($user);
	return $user[0]['username'];
	
}

function getConcepts($id)
{
	$q = Doctrine_Query::create()
	->select('e.question_id,  e.concept_id')
	->from('QuestionConcept e')
	->where('e.question_id = ? AND e.run_id = ?', array($id,$_SESSION['run_id']));
	 
	$result = $q->fetchArray();

	return $result;
}

function countVotes($obj_id, $obj_type)
{
	// get all votes for this post: note that we can use SUM in SQL instead
	// ********************************************************************* 
    $q = Doctrine_Query::create()
	//->select ("v.id, v.vote_value, u.id, u.username") // use this if we want to show who and how someone voted
	->select ("v.id, v.vote_value")
	->from("Vote v")
	//->innerJoin("v.User u")
	->where('v.run_id = ? AND v.obj_id = ? AND v.obj_type = ?' , 
	array($_SESSION['run_id'],$obj_id, $obj_type)) 				
	->orderBy('v.id DESC');
	
	$votes = $q->fetchArray();

	$votesCount = array();
	$votesSumm = 0; $votesMinus = 0; $votesPlus = 0;
	
	foreach ($votes as $vote)
	{
		$votesSumm += $vote['vote_value'];
		
		if($vote['vote_value']==-1)
		{
			$votesMinus-= $vote['vote_value'];
		} else {
			$votesPlus+= $vote['vote_value'];
		}
		
	}
	$votesCount = array (
		"votesSumm" => $votesSumm,
		"votesMinus" => $votesMinus,
		"votesPlus" => $votesPlus
	);
	return $votesCount;
	// end get votes
	
} // end countVotes()

function analyzeTags($tags, $prefix="")
{
	$prefix = "qe_"; // same for voting on question_concept and example_concept 

	//get all Concepts in db for comparison: which ones are not added yet
	$q = Doctrine_Query::create()
		->select('e.id,  e.name')
		->from('Concept e')
		->where('e.run_id = ?', $_SESSION['run_id']);
	
	$theConcepts = $q->fetchArray();
	
	//$theConcepts=Doctrine::getTable("Concepts")->findAll(Doctrine::HYDRATE_ARRAY);
	
	//print_r($theConcepts);
	//print_r($tags);
	
	$currentConcepts = array(); // collects the concepts already associated to the example
	//$notIncludedConcepts = array();
	$theConceptsF = array(); // formats the concepts in db to same structure than current $currentConcepts

	//$PLACEWEB_CONFIG['fConcepts']
	
	$tagsHtml = "";
	$notIncludedConceptsHtml = "";
	
	$whoHasVoted = array();
	$conn=0;
	
	// adjust the concepts from db 
	foreach($theConcepts as $concept)
	{
		$theConceptsF[$concept['id']] = $concept['name'];
	}
	
	//print_r($theConceptsF);
	
	foreach ($tags as $tag)
	{
		/* 
		 * get votes data
		 */ 

			// collect tags for comparison 
			$currentConcepts[$tag['concept_id']] = $theConceptsF[$tag['concept_id']];
			
		
		//var_dump($tag);
		//echo "<br/>".$tag['conceptId'];
		
			$votesCount = countVotes($tag['concept_id'],5); // look for votes for obj_type = 4 example_concept
			
			$votesMinus =0 ;
			$votesSumm = 0;
			$votesPlus = 0;
		
		$tagsHtml .='
		<li>
			<div class="tag-name">'.$theConceptsF[$tag['concept_id']].'</div>
			<div class="votes-container" style="float:right;">
				<div  id="'.$prefix.'vote-loading-'.$tag['concept_id'].'"></div> 
				<div  id="'.$prefix.'vote-minus-'.$tag['concept_id'].'" class="vote-minus-plus">
					'.$votesCount['votesMinus'].'
				</div> 
				<div class="vote-icon">
					<a href="javascript:postVote(-1,'.$tag['concept_id'].',5,'.$_SESSION['author_id'].',\''.$prefix.'\');"><img src="/images/icon_arrow_down.png" width="20px"></a>
				</div>
				<div  id="'.$prefix.'vote-total-'.$tag['concept_id'].'" class="vote-total">
					'.$votesCount['votesSumm'].'
				</div>
				<div class="vote-icon">
					<a href="javascript:postVote(1,'.$tag['concept_id'].',5,'.$_SESSION['author_id'].',\''.$prefix.'\');"><img src="/images/icon_arrow_up.png" width="20px"></a>
				</div>
				<div  id="'.$prefix.'vote-plus-'.$tag['concept_id'].'" class="vote-minus-plus">
					'.$votesCount['votesPlus'].'
				</div> 
			</div>
		</li>';
			
			$conn++;
	}
	
	$notIncludedConcepts = array_diff($theConceptsF, $currentConcepts);

	//print_r($currentConcepts);
	//print_r($notIncludedConcepts);
	
	$notIncludedConceptsHtml = "
	<li> &nbsp; 
	</li>
	";
	
	// not included tags
	foreach ($notIncludedConcepts as $diffTagId => $diffTagVal)
	{
		$notIncludedConceptsHtml .='
		<li>
			<div class="tag-name">'.$diffTagVal.'</div>
			<div class="tag-add"><a href="javascript:addTag(\''.$diffTagId.'\');">[Add]</a></div>
		</li>';
		
		//echo "<br/>".$diffTagId;
	} 
	
	return $tagsHtml.$notIncludedConceptsHtml;

} // end fnc


?>