<!DOCTYPE html>
<!--<?php 
echo $this->doctype() ?>-->
<html>
<head>
  <!-- To be HTML5 we do this -->
  <!-- <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> -->
  <meta charset="utf-8" />

  <title>PLACE.web</title>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js"></script>
    
    <script type="text/javascript" src="/jquery/jqueryfileupload/jquery.iframe-transport.js"></script>
    <script type="text/javascript" src="/jquery/jqueryfileupload/jquery.fileupload.js"></script>
    <script type="text/javascript" src="/jquery/jqueryfileupload/jquery.fileupload-ui.js"></script>
    
    <script type="text/javascript" src="/jquery/jplayer/jquery.jplayer.min.js"></script>
    <script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js"></script>
    
    <link type="text/css" rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/smoothness/jquery-ui.css" />
    <link type="text/css" rel="stylesheet" href="/jquery/jqueryfileupload/jquery.fileupload-ui.css" />
    <link type="text/css" rel="stylesheet" href="/jquery/jplayer/themes/blue.monday/jplayer.blue.monday.css" />

	<script src="/js/basic.js" type="text/javascript" ></script>
	<link type="text/css" href="/css/styles.css" rel="stylesheet" />

<!-- testing slider -->
	<script type="text/javascript" src="/jquery/selectToUISlider/js/selectToUISlider.jQuery.js"></script>
	<link rel="stylesheet" href="/jquery/selectToUISlider/css/redmond/jquery-ui-1.7.1.custom.css" type="text/css" />
	<link rel="Stylesheet" href="/jquery/selectToUISlider/css/ui.slider.extras.css" type="text/css" />
<!-- /testing slider -->

	<script type="text/javascript">
		
$(document).ready(function () {
	  $("#viz-loader").html("");
	  $("#viz-loader").addClass('div-hide');
	  $("#viz-container").removeClass('div-hide');
<?php 
// set viz mode
if($this->vizType==1)
{
	echo "	init();";	
} else if($this->vizType==2) {
	echo "	init2();";	
} else if($this->vizType==3) {
	echo "	init3();";	
}
?>
<?php 
		if($this->valueAA!="")
		{
		?>
		    $("#valueAA option[value='<?php echo $this->valueAA;?>']").attr('selected', 'selected');
		<?php
		}
		?>
		<?php 
		if($this->valueBB!="")
		{
		?>
		    $("#valueBB option[value='<?php echo $this->valueBB;?>']").attr('selected', 'selected');
		<?php
		}
		?>
		$(function(){
			$('select#valueAA, select#valueBB').selectToUISlider({
				labels: 0,
				labelSrc: "text",
				tooltip: true,
				tooltipSrc: "text",
				
			});
		});
});
</script>
</head>
<body>
<?php 
//generateDateList('valueTT');
?>
<div id="viz-loader"><img src='/images/loader.gif' alt='Loading Icon' /></div>
<div id="viz-container" class="div-hide">
	
	<!-- CSS Files for each viz-->
	<link type="text/css" href="/js/viz/css/base.css" rel="stylesheet" />
	<?php 
	if($this->vizType==2)
	{
		echo '
	<link type="text/css" href="/js/viz/css/Hypertree.css" rel="stylesheet" />
';
	} else if ($this->vizType==3){
		echo '
	<link type="text/css" href="/js/viz/css/ForceDirected.css" rel="stylesheet" />
';
	}
	?>

	<!--[if IE]><script language="javascript" type="text/javascript" src="/js/viz/Extras/excanvas.js"></script><![endif]-->

	<!-- JIT Library File -->
	<script language="javascript" type="text/javascript" src="/js/viz/jit.js"></script>
	<script language="javascript" type="text/javascript" src="/js/viz/jit-yc.js"></script>

	<?php 
	$conceptIdUrlEncode = "";
	if(isset($this->conceptId))
	{
		foreach ($this->conceptId as $conceptId)
		{
			$conceptIdUrlEncode .= "&conceptId%5B%5D=".$conceptId;
		}
	}
	?>
	<script language="javascript" type="text/javascript" src="/web/getd3json?vizDate=<?php echo $this->vizDate?>&valueAA=<?php echo $this->valueAA?>&valueBB=<?php echo $this->valueBB?>&keyW=<?php echo $this->keyW?>&vizVo=<?php echo $this->vizVo?>&vizType=<?php echo $this->vizType?>&vizEx=<?php echo $this->vizEx?>&vizQu=<?php echo $this->vizQu?>&vizMy=<?php echo $this->vizMy?>&vizCon=<?php echo $this->vizCon?><?php echo $conceptIdUrlEncode?>"></script>
<form action="<?php $_SERVER['PHP_SELF']?>" method="get">
	<div id="web-controls">
		<div class="control"> 
			Graph: <select name="vizType">
			<!-- 
				<option value="1" <?php if($this->vizType==1) {echo ' selected="selected"';} ?>>HyperTree</option>
			-->
				<option value="2" <?php if($this->vizType==2) {echo ' selected="selected"';} ?>>RGraph</option>
				<option value="3" <?php if($this->vizType==3) {echo ' selected="selected"';} ?>>Force Directed</option>
			</select> | 
		</div>

		<div class="control">
			<input <?php if($this->vizEx==1) {echo ' checked="checked"';} ?>type="checkbox" name="vizEx" value="1"> Examples |
			<input <?php if($this->vizQu==1) {echo ' checked="checked"';} ?>type="checkbox" name="vizQu" value="1"> Questions |
			<input <?php if($this->vizVo==1) {echo ' checked="checked"';} ?>type="checkbox" name="vizVo" value="1"> Votes |
			<input <?php if($this->vizMy==1) {echo ' checked="checked"';} ?>type="checkbox" name="vizMy" value="1"> My Contributions |
		</div>
		<div style="margin-top: 2px; margin-left: 4px;" class="control"> Filter by Concept </div>
		<div style="margin-top: 4px; margin-left: 4px;" class="control" id="concept-select-link"> <a href="#" onClick="showConceptList()"><img width="13px" height="13px" src="/images/icon_list_arrow_rigth.png" alt="Show Concepts"/></a> </div>
	
		<div id="concept-select-list" class="div-hide">
	<?php 
	//         // get concepts for current run_id
	        $concepts = Doctrine::getTable("Concept")
	                 ->findByDql("run_id = ?", $_SESSION['run_id']);

			$conceptsList = '
			<select name="conceptId[]" size=10 multiple>
				<option value="0"> - Show All Concepts</option>		
			';

			foreach ($concepts as $concept)
	        {
	        	$selected="";
	        	//if($concept->id==$this->conceptId) 
	        	if(in_array($concept->id, $this->conceptId))
	        	{
	        		$selected = ' selected="selected"';
	        	}
	        	$conceptsList .= '
	        	<option value="'.$concept->id.'"'.$selected.'>'.$concept->name.'</option>';
	        }
	        $conceptsList .= '
	        </select>';

	        echo $conceptsList;
	?>
		</div>
		| <input <?php if($this->vizDate==1) {echo ' checked="checked"';} ?>type="checkbox" name="vizDate" value="1"> Filter by Dates
		<br/><br/><input type="text" id="keyW" name="keyW" value="<?php echo $this->keyW;?>" title="Search keyword(s)"/>  
	
		<input type="submit" value="Refresh" />
		<div class="clear"></div>
		<div id="time-slider">
		<fieldset>
			<div id="time-controls">
				<select id="valueAA" name="valueAA">
					<optgroup label="Sep-2011">
						<option value="1314892800">Sep 1</option>
						<option value="1314979200">Sep 2</option>
						<option value="1315065600">Sep 3</option>
						<option value="1315152000">Sep 4</option>
						<option value="1315238400">Sep 5</option>
						<option value="1315324800">Sep 6</option>
						<option value="1315411200">Sep 7</option>
						<option value="1315497600">Sep 8</option>
						<option value="1315584000">Sep 9</option>
						<option value="1315670400">Sep 10</option>
						<option value="1315756800">Sep 11</option>
						<option value="1315843200">Semberep 12</option>
						<option value="1315929600">Sep 13</option>
						<option value="1316016000">Sep 14</option>
						<option value="1316102400">Sep 15</option>
						<option value="1316188800">Sep 16</option>
						<option value="1316275200">Sep 17</option>
						<option value="1316361600">Sep 18</option>
						<option value="1316448000">Sep 19</option>
						<option value="1316534400">Sep 20</option>
						<option value="1316620800">Sep 21</option>
						<option value="1316707200">Sep 22</option>
						<option value="1316793600">Sep 23</option>
						<option value="1316880000">Sep 24</option>
						<option value="1316966400">Sep 25</option>
						<option value="1317052800">Sep 26</option>
						<option value="1317139200">Sep 27</option>
						<option value="1317225600">Sep 28</option>
						<option value="1317312000">Sep 29</option>
						<option value="1317398400">Sep 30</option>
					</optgroup>
					<optgroup label="Oct-2011">
						<option value="1317484800">Oct 1</option>
						<option value="1317571200">Oct 2</option>
						<option value="1317657600">Oct 3</option>
						<option value="1317744000">Oct 4</option>
						<option value="1317830400">Oct 5</option>
						<option value="1317916800">Oct 6</option>
						<option value="1318003200">Oct 7</option>
						<option value="1318089600">Oct 8</option>
						<option value="1318176000">Oct 9</option>
						<option value="1318262400">Oct 10</option>
						<option value="1318348800">Oct 11</option>
						<option value="1318435200">Oct 12</option>
						<option value="1318521600">Oct 13</option>
						<option value="1318608000">Oct 14</option>
						<option value="1318694400">Oct 15</option>
						<option value="1318780800">Oct 16</option>
						<option value="1318867200">Oct 17</option>
						<option value="1318953600">Oct 18</option>
						<option value="1319040000">Oct 19</option>
						<option value="1319126400">Oct 20</option>
						<option value="1319212800">Oct 21</option>
						<option value="1319299200">Oct 22</option>
						<option value="1319385600">Oct 23</option>
						<option value="1319472000">Oct 24</option>
						<option value="1319558400">Oct 25</option>
						<option value="1319644800">Oct 26</option>
						<option value="1319731200">Oct 27</option>
						<option value="1319817600">Oct 28</option>
						<option value="1319904000">Oct 29</option>
						<option value="1319994000">Oct 30</option>
						<option value="1320080400">Oct 31</option>
					</optgroup>
					<optgroup label="Nov-2011">
						<option value="1320166800">Nov 1</option>
						<option value="1320253200">Nov 2</option>
						<option value="1320339600">Nov 3</option>
						<option value="1320426000">Nov 4</option>
						<option value="1320512400">Nov 5</option>
						<option value="1320598800">Nov 6</option>
						<option value="1320685200">Nov 7</option>
						<option value="1320771600">Nov 8</option>
						<option value="1320858000">Nov 9</option>
						<option value="1320944400">Nov 10</option>
						<option value="1321030800">Nov 11</option>
						<option value="1321117200">Nov 12</option>
						<option value="1321203600">Nov 13</option>
						<option value="1321290000">Nov 14</option>
						<option value="1321376400">Nov 15</option>
						<option value="1321462800">Nov 16</option>
						<option value="1321549200">Nov 17</option>
						<option value="1321635600">Nov 18</option>
						<option value="1321722000">Nov 19</option>
						<option value="1321808400">Nov 20</option>
						<option value="1321894800">Nov 21</option>
						<option value="1321981200">Nov 22</option>
						<option value="1322067600">Nov 23</option>
						<option value="1322154000">Nov 24</option>
						<option value="1322240400">Nov 25</option>
						<option value="1322326800">Nov 26</option>
						<option value="1322413200">Nov 27</option>
						<option value="1322499600">Nov 28</option>
						<option value="1322586000">Nov 29</option>
						<option value="1322672400">Nov 30</option>
					</optgroup>
					<optgroup label="Dec-2011">
						<option value="1322758800">Dec 1</option>
						<option value="1322845200">Dec 2</option>
						<option value="1322931600">Dec 3</option>
						<option value="1323018000">Dec 4</option>
						<option value="1323104400">Dec 5</option>
						<option value="1323190800">Dec 6</option>
						<option value="1323277200">Dec 7</option>
						<option value="1323363600">Dec 8</option>
						<option value="1323450000">Dec 9</option>
						<option value="1323536400">Dec 10</option>
						<option value="1323622800">Dec 11</option>
						<option value="1323709200">Dec 12</option>
						<option value="1323795600">Dec 13</option>
						<option value="1323882000">Dec 14</option>
						<option value="1323968400">Dec 15</option>
						<option value="1324054800">Dec 16</option>
						<option value="1324141200">Dec 17</option>
						<option value="1324227600">Dec 18</option>
						<option value="1324314000">Dec 19</option>
						<option value="1324400400">Dec 20</option>
						<option value="1324486800">Dec 21</option>
						<option value="1324573200">Dec 22</option>
						<option value="1324659600">Dec 23</option>
						<option value="1324746000">Dec 24</option>
						<option value="1324832400">Dec 25</option>
						<option value="1324918800">Dec 26</option>
						<option value="1325005200">Dec 27</option>
						<option value="1325091600">Dec 28</option>
						<option value="1325178000">Dec 29</option>
						<option value="1325264400">Dec 30</option>
						<option value="1325350800">Dec 31</option>
					</optgroup>
					<optgroup label="Jan-2012">
						<option value="1325437200">Jan 1</option>
						<option value="1325523600">Jan 2</option>
						<option value="1325610000">Jan 3</option>
						<option value="1325696400">Jan 4</option>
						<option value="1325782800">Jan 5</option>
						<option value="1325869200">Jan 6</option>
						<option value="1325955600">Jan 7</option>
						<option value="1326042000">Jan 8</option>
						<option value="1326128400">Jan 9</option>
						<option value="1326214800">Jan 10</option>
						<option value="1326301200">Jan 11</option>
						<option value="1326387600">Jan 12</option>
						<option value="1326474000">Jan 13</option>
						<option value="1326560400">Jan 14</option>
						<option value="1326646800">Jan 15</option>
						<option value="1326733200">Jan 16</option>
						<option value="1326819600">Jan 17</option>
						<option value="1326906000">Jan 18</option>
						<option value="1326992400">Jan 19</option>
						<option value="1327078800">Jan 20</option>
						<option value="1327165200">Jan 21</option>
						<option value="1327251600">Jan 22</option>
						<option value="1327338000">Jan 23</option>
						<option value="1327424400">Jan 24</option>
						<option value="1327510800">Jan 25</option>
						<option value="1327597200">Jan 26</option>
						<option value="1327683600">Jan 27</option>
						<option value="1327770000">Jan 28</option>
						<option value="1327856400">Jan 29</option>
						<option value="1327942800">Jan 30</option>
						<option value="1328029200">Jan 31</option>
					</optgroup>
					<optgroup label="Feb-2012">
						<option value="1328115600">Feb 1</option>
						<option value="1328202000">Feb 2</option>
						<option value="1328288400">Feb 3</option>
						<option value="1328374800">Feb 4</option>
						<option value="1328461200">Feb 5</option>
						<option value="1328547600">Feb 6</option>
						<option value="1328634000">Feb 7</option>
						<option value="1328720400">Feb 8</option>
						<option value="1328806800">Feb 9</option>
						<option value="1328893200">Feb 10</option>
						<option value="1328979600">Feb 11</option>
						<option value="1329066000">Feb 12</option>
						<option value="1329152400">Feb 13</option>
						<option value="1329238800">Feb 14</option>
						<option value="1329325200">Feb 15</option>
						<option value="1329411600">Feb 16</option>
						<option value="1329498000">Feb 17</option>
						<option value="1329584400">Feb 18</option>
						<option value="1329670800">Feb 19</option>
						<option value="1329757200">Feb 20</option>
						<option value="1329843600">Feb 21</option>
						<option value="1329930000">Feb 22</option>
						<option value="1330016400">Feb 23</option>
						<option value="1330102800">Feb 24</option>
						<option value="1330189200">Feb 25</option>
						<option value="1330275600">Feb 26</option>
						<option value="1330362000">Feb 27</option>
						<option value="1330448400">Feb 28</option>
						<option value="1330534800">Feb 29</option>
					</optgroup>
					<optgroup label="Mar-2012">
						<option value="1330621200">Mar 1</option>
						<option value="1330707600">Mar 2</option>
						<option value="1330794000">Mar 3</option>
						<option value="1330880400">Mar 4</option>
						<option value="1330966800">Mar 5</option>
						<option value="1331053200">Mar 6</option>
						<option value="1331139600">Mar 7</option>
						<option value="1331226000">Mar 8</option>
						<option value="1331312400">Mar 9</option>
						<option value="1331398800">Mar 10</option>
						<option value="1331481600">Mar 11</option>
						<option value="1331568000">Mar 12</option>
						<option value="1331654400">Mar 13</option>
						<option value="1331740800">Mar 14</option>
						<option value="1331827200">Mar 15</option>
						<option value="1331913600">Mar 16</option>
						<option value="1332000000">Mar 17</option>
						<option value="1332086400">Mar 18</option>
						<option value="1332172800">Mar 19</option>
						<option value="1332259200">Mar 20</option>
						<option value="1332345600">Mar 21</option>
						<option value="1332432000">Mar 22</option>
						<option value="1332518400">Mar 23</option>
						<option value="1332604800">Mar 24</option>
						<option value="1332691200">Mar 25</option>
						<option value="1332777600">Mar 26</option>
						<option value="1332864000">Mar 27</option>
						<option value="1332950400">Mar 28</option>
						<option value="1333036800">Mar 29</option>
						<option value="1333123200">Mar 30</option>
						<option value="1333209600">Mar 31</option>
					</optgroup>
					<optgroup label="Apr-2012">
						<option value="1333296000">Apr 1</option>
						<option value="1333382400">Apr 2</option>
						<option value="1333468800">Apr 3</option>
						<option value="1333555200">Apr 4</option>
						<option value="1333641600">Apr 5</option>
						<option value="1333728000">Apr 6</option>
						<option value="1333814400">Apr 7</option>
						<option value="1333900800">Apr 8</option>
						<option value="1333987200">Apr 9</option>
						<option value="1334073600">Apr 10</option>
						<option value="1334160000">Apr 11</option>
						<option value="1334246400">Apr 12</option>
						<option value="1334332800">Apr 13</option>
						<option value="1334419200">Apr 14</option>
						<option value="1334505600">Apr 15</option>
						<option value="1334592000">Apr 16</option>
						<option value="1334678400">Apr 17</option>
						<option value="1334764800">Apr 18</option>
						<option value="1334851200">Apr 19</option>
						<option value="1334937600">Apr 20</option>
						<option value="1335024000">Apr 21</option>
						<option value="1335110400">Apr 22</option>
						<option value="1335196800">Apr 23</option>
						<option value="1335283200">Apr 24</option>
						<option value="1335369600">Apr 25</option>
						<option value="1335456000">Apr 26</option>
						<option value="1335542400">Apr 27</option>
						<option value="1335628800">Apr 28</option>
						<option value="1335715200">Apr 29</option>
						<option value="1335801600">Apr 30</option>
					</optgroup>
				</select>
				<select name="valueBB" id="valueBB">
					<optgroup label="Sep-2011">
						<option value="1314892800">Sep 1</option>
						<option value="1314979200">Sep 2</option>
						<option value="1315065600">Sep 3</option>
						<option value="1315152000">Sep 4</option>
						<option value="1315238400">Sep 5</option>
						<option value="1315324800">Sep 6</option>
						<option value="1315411200">Sep 7</option>
						<option value="1315497600">Sep 8</option>
						<option value="1315584000">Sep 9</option>
						<option value="1315670400">Sep 10</option>
						<option value="1315756800">Sep 11</option>
						<option value="1315843200">Sep 12</option>
						<option value="1315929600">Sep 13</option>
						<option value="1316016000">Sep 14</option>
						<option value="1316102400">Sep 15</option>
						<option value="1316188800">Sep 16</option>
						<option value="1316275200">Sep 17</option>
						<option value="1316361600">Sep 18</option>
						<option value="1316448000">Sep 19</option>
						<option value="1316534400">Sep 20</option>
						<option value="1316620800">Sep 21</option>
						<option value="1316707200">Sep 22</option>
						<option value="1316793600">Sep 23</option>
						<option value="1316880000">Sep 24</option>
						<option value="1316966400">Sep 25</option>
						<option value="1317052800">Sep 26</option>
						<option value="1317139200">Sep 27</option>
						<option value="1317225600">Sep 28</option>
						<option value="1317312000">Sep 29</option>
						<option value="1317398400">Sep 30</option>
					</optgroup>
					<optgroup label="Oct-2011">
						<option value="1317484800">Oct 1</option>
						<option value="1317571200">Oct 2</option>
						<option value="1317657600">Oct 3</option>
						<option value="1317744000">Oct 4</option>
						<option value="1317830400">Oct 5</option>
						<option value="1317916800">Oct 6</option>
						<option value="1318003200">Oct 7</option>
						<option value="1318089600">Oct 8</option>
						<option value="1318176000">Oct 9</option>
						<option value="1318262400">Oct 10</option>
						<option value="1318348800">Oct 11</option>
						<option value="1318435200">Oct 12</option>
						<option value="1318521600">Oct 13</option>
						<option value="1318608000">Oct 14</option>
						<option value="1318694400">Oct 15</option>
						<option value="1318780800">Oct 16</option>
						<option value="1318867200">Oct 17</option>
						<option value="1318953600">Oct 18</option>
						<option value="1319040000">Oct 19</option>
						<option value="1319126400">Oct 20</option>
						<option value="1319212800">Oct 21</option>
						<option value="1319299200">Oct 22</option>
						<option value="1319385600">Oct 23</option>
						<option value="1319472000">Oct 24</option>
						<option value="1319558400">Oct 25</option>
						<option value="1319644800">Oct 26</option>
						<option value="1319731200">Oct 27</option>
						<option value="1319817600">Oct 28</option>
						<option value="1319904000">Oct 29</option>
						<option value="1319994000">Oct 30</option>
						<option value="1320080400">Oct 31</option>
					</optgroup>
					<optgroup label="Nov-2011">
						<option value="1320166800">Nov 1</option>
						<option value="1320253200">Nov 2</option>
						<option value="1320339600">Nov 3</option>
						<option value="1320426000">Nov 4</option>
						<option value="1320512400">Nov 5</option>
						<option value="1320598800">Nov 6</option>
						<option value="1320685200">Nov 7</option>
						<option value="1320771600">Nov 8</option>
						<option value="1320858000">Nov 9</option>
						<option value="1320944400">Nov 10</option>
						<option value="1321030800">Nov 11</option>
						<option value="1321117200">Nov 12</option>
						<option value="1321203600">Nov 13</option>
						<option value="1321290000">Nov 14</option>
						<option value="1321376400">Nov 15</option>
						<option value="1321462800">Nov 16</option>
						<option value="1321549200">Nov 17</option>
						<option value="1321635600">Nov 18</option>
						<option value="1321722000">Nov 19</option>
						<option value="1321808400">Nov 20</option>
						<option value="1321894800">Nov 21</option>
						<option value="1321981200">Nov 22</option>
						<option value="1322067600">Nov 23</option>
						<option value="1322154000">Nov 24</option>
						<option value="1322240400">Nov 25</option>
						<option value="1322326800">Nov 26</option>
						<option value="1322413200">Nov 27</option>
						<option value="1322499600">Nov 28</option>
						<option value="1322586000">Nov 29</option>
						<option value="1322672400">Nov 30</option>
					</optgroup>
					<optgroup label="Dec-2011">
						<option value="1322758800">Dec 1</option>
						<option value="1322845200">Dec 2</option>
						<option value="1322931600">Dec 3</option>
						<option value="1323018000">Dec 4</option>
						<option value="1323104400">Dec 5</option>
						<option value="1323190800">Dec 6</option>
						<option value="1323277200">Dec 7</option>
						<option value="1323363600">Dec 8</option>
						<option value="1323450000">Dec 9</option>
						<option value="1323536400">Dec 10</option>
						<option value="1323622800">Dec 11</option>
						<option value="1323709200">Dec 12</option>
						<option value="1323795600">Dec 13</option>
						<option value="1323882000">Dec 14</option>
						<option value="1323968400">Dec 15</option>
						<option value="1324054800">Dec 16</option>
						<option value="1324141200">Dec 17</option>
						<option value="1324227600">Dec 18</option>
						<option value="1324314000">Dec 19</option>
						<option value="1324400400">Dec 20</option>
						<option value="1324486800">Dec 21</option>
						<option value="1324573200">Dec 22</option>
						<option value="1324659600">Dec 23</option>
						<option value="1324746000">Dec 24</option>
						<option value="1324832400">Dec 25</option>
						<option value="1324918800">Dec 26</option>
						<option value="1325005200">Dec 27</option>
						<option value="1325091600">Dec 28</option>
						<option value="1325178000">Dec 29</option>
						<option value="1325264400">Dec 30</option>
						<option value="1325350800">Dec 31</option>
					</optgroup>
					<optgroup label="Jan-2012">
						<option value="1325437200">Jan 1</option>
						<option value="1325523600">Jan 2</option>
						<option value="1325610000">Jan 3</option>
						<option value="1325696400">Jan 4</option>
						<option value="1325782800">Jan 5</option>
						<option value="1325869200">Jan 6</option>
						<option value="1325955600">Jan 7</option>
						<option value="1326042000">Jan 8</option>
						<option value="1326128400">Jan 9</option>
						<option value="1326214800">Jan 10</option>
						<option value="1326301200">Jan 11</option>
						<option value="1326387600">Jan 12</option>
						<option value="1326474000">Jan 13</option>
						<option value="1326560400">Jan 14</option>
						<option value="1326646800">Jan 15</option>
						<option value="1326733200">Jan 16</option>
						<option value="1326819600">Jan 17</option>
						<option value="1326906000">Jan 18</option>
						<option value="1326992400">Jan 19</option>
						<option value="1327078800">Jan 20</option>
						<option value="1327165200">Jan 21</option>
						<option value="1327251600">Jan 22</option>
						<option value="1327338000">Jan 23</option>
						<option value="1327424400">Jan 24</option>
						<option value="1327510800">Jan 25</option>
						<option value="1327597200">Jan 26</option>
						<option value="1327683600">Jan 27</option>
						<option value="1327770000">Jan 28</option>
						<option value="1327856400">Jan 29</option>
						<option value="1327942800">Jan 30</option>
						<option value="1328029200">Jan 31</option>
					</optgroup>
					<optgroup label="Feb-2012">
						<option value="1328115600">Feb 1</option>
						<option value="1328202000">Feb 2</option>
						<option value="1328288400">Feb 3</option>
						<option value="1328374800">Feb 4</option>
						<option value="1328461200">Feb 5</option>
						<option value="1328547600">Feb 6</option>
						<option value="1328634000">Feb 7</option>
						<option value="1328720400">Feb 8</option>
						<option value="1328806800">Feb 9</option>
						<option value="1328893200">Feb 10</option>
						<option value="1328979600">Feb 11</option>
						<option value="1329066000">Feb 12</option>
						<option value="1329152400">Feb 13</option>
						<option value="1329238800">Feb 14</option>
						<option value="1329325200">Feb 15</option>
						<option value="1329411600">Feb 16</option>
						<option value="1329498000">Feb 17</option>
						<option value="1329584400">Feb 18</option>
						<option value="1329670800">Feb 19</option>
						<option value="1329757200">Feb 20</option>
						<option value="1329843600">Feb 21</option>
						<option value="1329930000">Feb 22</option>
						<option value="1330016400">Feb 23</option>
						<option value="1330102800">Feb 24</option>
						<option value="1330189200">Feb 25</option>
						<option value="1330275600">Feb 26</option>
						<option value="1330362000">Feb 27</option>
						<option value="1330448400">Feb 28</option>
						<option value="1330534800">Feb 29</option>
					</optgroup>
					<optgroup label="Mar-2012">
						<option value="1330621200">Mar 1</option>
						<option value="1330707600">Mar 2</option>
						<option value="1330794000">Mar 3</option>
						<option value="1330880400">Mar 4</option>
						<option value="1330966800">Mar 5</option>
						<option value="1331053200">Mar 6</option>
						<option value="1331139600">Mar 7</option>
						<option value="1331226000">Mar 8</option>
						<option value="1331312400">Mar 9</option>
						<option value="1331398800">Mar 10</option>
						<option value="1331481600">Mar 11</option>
						<option value="1331568000">Mar 12</option>
						<option value="1331654400">Mar 13</option>
						<option value="1331740800">Mar 14</option>
						<option value="1331827200">Mar 15</option>
						<option value="1331913600">Mar 16</option>
						<option value="1332000000">Mar 17</option>
						<option value="1332086400">Mar 18</option>
						<option value="1332172800">Mar 19</option>
						<option value="1332259200">Mar 20</option>
						<option value="1332345600">Mar 21</option>
						<option value="1332432000">Mar 22</option>
						<option value="1332518400">Mar 23</option>
						<option value="1332604800">Mar 24</option>
						<option value="1332691200">Mar 25</option>
						<option value="1332777600">Mar 26</option>
						<option value="1332864000">Mar 27</option>
						<option value="1332950400">Mar 28</option>
						<option value="1333036800">Mar 29</option>
						<option value="1333123200">Mar 30</option>
						<option value="1333209600">Mar 31</option>
					</optgroup>
					<optgroup label="Apr-2012">
						<option value="1333296000">Apr 1</option>
						<option value="1333382400">Apr 2</option>
						<option value="1333468800">Apr 3</option>
						<option value="1333555200">Apr 4</option>
						<option value="1333641600">Apr 5</option>
						<option value="1333728000">Apr 6</option>
						<option value="1333814400">Apr 7</option>
						<option value="1333900800">Apr 8</option>
						<option value="1333987200">Apr 9</option>
						<option value="1334073600">Apr 10</option>
						<option value="1334160000">Apr 11</option>
						<option value="1334246400">Apr 12</option>
						<option value="1334332800">Apr 13</option>
						<option value="1334419200">Apr 14</option>
						<option value="1334505600">Apr 15</option>
						<option value="1334592000">Apr 16</option>
						<option value="1334678400">Apr 17</option>
						<option value="1334764800">Apr 18</option>
						<option value="1334851200">Apr 19</option>
						<option value="1334937600">Apr 20</option>
						<option value="1335024000">Apr 21</option>
						<option value="1335110400">Apr 22</option>
						<option value="1335196800">Apr 23</option>
						<option value="1335283200">Apr 24</option>
						<option value="1335369600">Apr 25</option>
						<option value="1335456000">Apr 26</option>
						<option value="1335542400">Apr 27</option>
						<option value="1335628800">Apr 28</option>
						<option value="1335715200">Apr 29</option>
						<option value="1335801600">Apr 30</option>
					</optgroup>					
				</select>
			</div>
		</fieldset>
		</div>
		<!-- /slider-->


	</div>
</form>


	<div id="log"></div>
	<div id="web-container">
		<div id="id-list"></div>
		<div id="center-container">
		<div id="infovis"></div>
		</div>

		<div id="right-container">
		<div id="inner-details"></div>
		</div>
	</div>
</div>

</body>
</html>