<?php
//<h3>/application/views/scripts/index/index.phtml</h3>
if(!$_SESSION['access'])
{
?>
	<div id="login-form">
		<form action="/" method="post">
			<label id="username-label" for="username">Username: </label>
			<input type="text" value="" id="username" name="username"/>
			</br>
			<label id="password-label" for="password">Password: </label>
			<input type="password" value="" id="password" name="password"/>
			</br>
			<label for="profile">Log in as: </label>
			<select name="profile" id="profile">
				<option value="TEACHER">Teacher</option>
				<option value="STUDENT">Student</option>
			</select>
			</br>
			<input id="login-button" type="submit" value="Login"/>
		</form>
	</div>
<?php 	
} else {
	header('Location: /myhome');
//echo "<hr/>User is loged in";
}
?>
