<?php
//<h3>/application/views/scripts/index/index.phtml</h3>
if(!$_SESSION['access'])
{
?>
	<div id="login-form">
		<form action="/" method="post">
			<span class="label">Username: </span>
			<input type="text" value="" id="username" name="username"/>
			<!-- 
			
			
			<select name="author_id">
			<option value="1">Teacher</option>
			<option value="2">Student1</option>
			<option value="3">Student2</option>
			<option value="4">Student3</option>
			-->

			</select>
			<br/><span class="label">Password: </span><input type="password" value="" id="password" name="password"/>
			<br/><br/>
			Log in as: 
			<select name="profile" id="profile">
				<option value="TEACHER">Teacher</option>
				<option value="STUDENT">Student</option>
			</select>
			<br/><br/>
			<input type="submit" value="Login"/>
		</form>
	</div>
<?php 	
} else {
	header('Location: /myhome');
//echo "<hr/>User is loged in";
}
?>
