<?php
if(!isset($_SESSION['access']))
{
?>
	<div id="login-form">
		<form action="/user/login" method="post">
		    
            <label id="username-label" for="username">Username: </label>
            <input type="text" value="" id="username" name="username"/>
            </br>

            <label id="password-label" for="password">Password: </label>
            <input type="password" value="" id="password" name="password"/>
            <br/>
            
			<input id="login-button" class="ui-button ui-widget ui-state-default ui-corner-all" type="submit" value="Login"/>
		</form>
	</div>
<?php 	
} else {
	header('Location: /myhome');
}
?>
