<?php
//<h1>/application/views/scripts/ajax/classactivity.phtml</h1>
//print_r($this->activities = $activities;);
function getUserName($author_id)
{
	$q = Doctrine_Query::create()
	->select('u.username')	
	->from('User u')
	->where('u.id = ?', $author_id);
	 
	$user = $q->fetchArray();
	
	//print_r($user);
	return $user[0]['username'];
	
}

function getExampleName($example_id)
{
	$q = Doctrine_Query::create()
	->select('e.name')
	->from('Example e')
	->where('e.id = ?', $example_id);
	 
	$example = $q->fetchArray();
	
	//print_r($example);
	return $example[0]['name'];
}

function getQuestionName($question_id)
{
	$q = Doctrine_Query::create()
	->select('e.name')
	->from('Question e')
	->where('e.id = ?', $question_id);
	 
	$question = $q->fetchArray();
	
	//print_r($example);
	return $question[0]['name'];
}

//print_r($this->activities);
//print_r($this->activitiesTypes);

$actHtml='
			<div class="dashlet-title">Recent Class Activity</div>
			<div>
				<ul class="ul-for-data">

';

// loop through the activities and determine how to render each type
foreach ($this->activities as $activity)
{
	// add examples
	if($activity['activity_type_id']==11)
	{
		$actHtml.= '<li><div class="alert-example"><strong>'.getUserName($activity['author_id']).'</strong> created a new Example titeled: 
		<a href="/discussion?type=3&id='.$activity['i1'].'">'.getExampleName($activity['i1']).'</a></div></li>';
		
	}
	
	// add questions
	if($activity['activity_type_id']==12)
	{
		$actHtml.= '<li><div class="alert-question"><strong>'.getUserName($activity['author_id']).'</strong> created a new Question titeled: 
		<a href="/question/show?&id='.$activity['i1'].'">'.getQuestionName($activity['i1']).'</a></div></li>';
		
	}
	// add comments
	if($activity['activity_type_id']==7)
	{
		$actHtml.= '<li><div class="alert-comments"><strong>'.getUserName($activity['author_id']).'</strong> commented on an Example : 
		<a href="/discussion?type=3&id='.$activity['i1'].'&id1='.$activity['i2'].'">'.getExampleName($activity['i2']).'</a></div></li>';
		
	}
	
	// answerd a question
	if($activity['activity_type_id']==13)
	{
		$actHtml.= '<li><div class="alert-answer"><strong>'.getUserName($activity['author_id']).'</strong> answered a Question: 
		<a href="/question/show?&id='.$activity['i2'].'">'.getQuestionName($activity['i2']).'</a></div></li>';
		
	}
	
	
} // end loop


	$actHtml.='
				</ul>
			</div>	
	';
echo $actHtml;


// ACTIVITY TYPES
/*
id 	name 
1	voted on comment
2	voted on answer
3	voted on answer concept
4	voted on example concept
5	commented on comment
6	commented on answer
7	commented on example
8	assessed comment
9	assessed example
10	assessed answer
11	example added
12	question created

 */

?>
