<div>
    <ul class="ul-for-data">
<?php 

foreach ($this->unansweredQuestions as $question)
{
    $url = $question->getUrl();
    echo "<li><div class='alert'>Please answer <a href='$url'>".$question->name."</a></div></li>";
}

foreach($this->answeredQuestions as $question)
{
    $answer = $question['Answer'][0];
    $url = $question->getUrl();
    echo "<li>
			<span class='alert-close-btn' activityId='{$activity->id}'><img src='/images/icon_ok.png' /></span>
			<div class='alert'>You've answered <a href='$url'>".$question->name."</a></div>
		</li>"; 
}
?>
	</ul>
</div>