<style type='text/css'>
.alert-created-example{
    background: #FF9900;
}
.alert-comment-example	{
	background: #FFCC00;
}

.alert-comment-answer  {
    background: #FFCC00;
}

.alert-comment-comment  {
    background: #FFCC00;
}
</style>

<div id='studentActivities' class='dashlet-box'>
    <div class="dashlet-title">Student Activities</div>

    <div>
        <ul class="ul-for-data">
    
<?php 
foreach ($this->activities as $activity)
{
	echo "<li>".$activity->getMessage()."</li>";
}
?>
    	</ul>
    </div>
</div>
    