<div id="example-container">
<?php 
global $notAssessedItems;
$notAssessedItems="";

///echo "<hr/>";
//echo "<hr/>Type: ".$this->type;

//echo "<hr/>";
//print_r($this->example);

// do not attempt to show the example if the example was not found, return an error message
if($this->type==-1)
{
	$error=true;
	echo '<p class="error-msg">The example does not exist.</p>';
} else {
	$error=false;
}

if($this->type==-2)
{
	$error=true;
	echo '<p class="error-msg">No examples have been created.</p>';
} else {
	$error=false;
}



/*
 * multiple view
 */
if($this->type==0 && !$error)
{
	$examplesListHtml="
	<h2>examples</h2>
<ul>";

	foreach ($this->example as $example)
	{
		$examplesListHtml.= "		
		<li><a href='/example/show?id=".$example['id']."'>".$example['name']."</a></li>";
	}
	$examplesListHtml.="
	</ul>";
	
	echo $examplesListHtml;


} else if($this->type==1 && !$error) 

/*
 * start single view
 */
{
?>


	<div id="elo-tags" class="dashlet-box" style="width:30%; float:right;">
		<div class="dashlet-title">Tags</div>
		
		<!-- start  tags-container -->
		<div id="tags-container">
			<ul class="ul-for-data">
			<?php
			$Myconcepts=getConcepts($this->example[0]['id']);
			
			//print_r($Myconcepts);
			echo analyzeTags($Myconcepts);
			?>
			</ul>
		</div>
		<!-- /tags-container -->
	</div>
	
	<!-- start media container -->
	<?php
		// MIKE'S CODE TO MAKE THE UPLOAD VIEW WORK //////////////////////////// 
		$mediaFile = current($this->example);
		// need the determine the media type here
		
		if (preg_match("/video/i", $mediaFile['media_type']))
		{
			echo '
		<div class="dashlet-box-image">
          <div class="dashlet-title">'.$this->example[0]['name'].'</div>
			<div id="jp_container_1" class="jp-video jp-video-270p">
                        <div class="jp-type-single">
                                <div id="jquery_jplayer_1" class="jp-jplayer"></div>
                                <div class="jp-gui">
                                        <div class="jp-video-play">
                                                <a href="javascript:;" class="jp-video-play-icon" tabindex="1">play</a>
                                        </div>
                                        <div class="jp-interface">
                                                <div class="jp-progress">
                                                        <div class="jp-seek-bar">
                                                                <div class="jp-play-bar"></div>
                                                        </div>
                                                </div>
                                                <div class="jp-current-time"></div>
                                                <div class="jp-duration"></div>
                                                <div class="jp-title">
                                                        <ul>
                                                                <li>' . $mediaFile['name'] . '</li>
                                                        </ul>
                                                </div>
                                                <div class="jp-controls-holder">
                                                        <ul class="jp-controls">
                                                                <li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
                                                                <li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
                                                                <li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
                                                                <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
                                                                <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
                                                                <li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
                                                        </ul>
                                                        <div class="jp-volume-bar">
                                                                <div class="jp-volume-bar-value"></div>
                                                        </div>

                                                        <ul class="jp-toggles">
                                                                <li><a href="javascript:;" class="jp-full-screen" tabindex="1" title="full screen">full screen</a></li>
                                                                <li><a href="javascript:;" class="jp-restore-screen" tabindex="1" title="restore screen">restore screen</a></li>
                                                                <li><a href="javascript:;" class="jp-repeat" tabindex="1" title="repeat">repeat</a></li>
                                                                <li><a href="javascript:;" class="jp-repeat-off" tabindex="1" title="repeat off">repeat off</a></li>
                                                        </ul>
                                                </div>
                                        </div>
                                </div>
                                <div class="jp-no-solution">
                                        <span>Update Required</span>
                                        To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
                                </div>
                        </div>

                </div>
	</div>
		<script>
			$("#jquery_jplayer_1").jPlayer({
                                        ready: function() { // The $.jPlayer.event.ready event
                                           $(this).jPlayer("setMedia", { m4v: "' . $mediaFile['media_content'] .  '" }).jPlayer("play");
                                        },
                                        ended: function() { // The $.jPlayer.event.ended event
                                            //$(this).jPlayer("play"); // Repeat the media
                                        },
                                        size: {
                                                            width: "460px",
                                                            height: "270px",
                                                            cssClass: "jp-video-270p"
                                                    },

                                     solution:"html, flash",
                                     swfPath: "/jquery/jplayer",
                                     supplied: "m4v",
                                     errorAlerts: true
                                    });
		</script>
			';
			// ANTONIO ADDED THIS TO FIX ADD SOME SPACE AFTER 
			/// WELL DONE MIKE!!
			echo "<br/>";
			
		} else { 
			
echo '
<div class="dashlet-box-image">
    <div class="dashlet-title">'.$this->example[0]['name'].'</div>
	<div class="image-holder"><img src="'.$mediaFile['media_content'].'" title="'.$this->example[0]['name'].'" width="320px" /></div>
</div>';

		}
		//<img  height="240px" title="Drag and Drop a new Media File here..." alt="Drag and Drop a new Media File here..." src="/images/uploader.png" id="eloimg">
		?>	

<div class="clear"></div>
	
	<div><?php //echo $this->example[0]['content'];?></div>
	
	<!-- assessment comment form -->
	<form name="assessment-form" method="post" action="/assessment/add?prefix=assessComm_">			
		
	<div id="posts-list">
	<?php 
	// get first level comments
	$discussionHtml = "";
	$myComments = getCommentsIds($this->example[0]['id'],3); // first level type=3
	//print_r($myComments);
	///*
	// for each top level comment find its children
	foreach ($myComments as $comment)
	{
		$discussionHtml .= getCommentById($comment['id']); // first level type=3
		//echo "<br/>Comment Id: ".$comment['id'];
	}
	//*/
	echo $discussionHtml;
	?>
	</div>	<!--  /posts-list -->
	
	<div class="clear"></div>
	
	<div id="newThread-container">
		<input type="button" value="New Thread" onClick="postNewThread(<?php echo $this->example[0]['id']; ?>,3,<?php echo $this->example[0]['author_id']; ?>)"/>
	</div>
	
	<div class="clear"></div>
	
<?php 
	if($_SESSION['profile']=="TEACHER"){
?>
		<input type="hidden" name="assessComm_activity_type_id" id="assessComm_activity_type_id" value="8"/>
		<input type="hidden" name="assessComm_activity_on_user" id="assessComm_activity_on_user" value=""/>
		<input type="hidden" name="assessComm_i1" id="assessComm_i1" value="<?php echo $this->example[0]['id']; ?>"/>
		<input type="hidden" name="assessComm_i2" id="assessComm_i2" value=""/>
		<input type="hidden" name="assessComm_t1" id="assessComm_t1" value="Example"/>
		<input type="hidden" name="assessComm_t2" id="assessComm__t2" value="Comment"/>
		
		<div id="btn_submit_marks" class="div-show">
			<input id="btn_submit_marks" type="button" value="Submit Marks" onclick="showAssessmentReview()">
		</div>
		<div id="assessment-review-container" class="dashlet-box div-hide">
			<div class="dashlet-title">Assessment Review</div>
			<textarea name="review-log" rows="" cols="" name="assessment_review"></textarea>
			<input type="hidden" value="1" name="obj_type"> <!-- 1=comment -->
			
			<input type="hidden" value="<?php echo $this->example[0]['id']; ?>" name="parent_id">
			<input type="hidden" value="examples" name="parent_type">
			<input type="hidden" value="<?php echo $notAssessedItems; ?>" name="assesment_list">
			
			<br/>
			<input type="submit" value="Confirm">
			<input type="button" value="Cancel" onclick="marksCancel()">
		</div>
<?php 
	} // end if teacher
?>

	</form>
	<!-- /assessment comment form  -->
	
 
		<div class="clear"></div>
 	
 	<!--  Start add comment form -->
	<form method="post" action="/comment/add">
		<div id="orig-reply-container" class="dashlet-box div-hide" style="margin-top: 25px;">
                        <div id="reply-original-title" class="dashlet-title">Original Message</div>
			<div id="reply-original-msg"></div>
		</div>
		<div id="reply-container" class="dashlet-box div-hide">
			<div id="reply-new-title" class="dashlet-title"></div>
			<textarea rows="5" cols="25" name="replyText" name="replyText"></textarea>
			<br/>
			<input type="submit" value="Submit"/>
			<input type="button" value="Cancel" onClick="postCancel()"/>
			<input type="hidden" name="obj_id" id="obj_id" value="<?php echo $this->example[0]['id']; ?>"/>
			<input type="hidden" name="postId" id="postId" value=""/>
			<input type="hidden" name="example_id" id="example_id" value="<?php echo $this->example[0]['id']; ?>"/>
			<input type="hidden" name="parentType" id="parentType" value=""/>
			<input type="hidden" name="activity_on_user" id="activity_on_user" value=""/>
			<input type="hidden" name="replyPosted" id="replyPosted" value="1"/>
		</div>
	</form>
	
	<!--  end add comment form -->		

	<!--  start add vote on comments -->
	<form id="comm_vote_form" method="post" action="/votes/add?prefix=comm_">
		<input type="hidden" name="comm_obj_id" id="comm_obj_id" value=""/>
		<input type="hidden" name="comm_obj_type" id="comm_obj_type" value="1"/>
		<input type="hidden" name="comm_vote_value" id="comm_vote_value" value=""/>
		<input type="hidden" name="comm_activity_type_id" id="comm_activity_type_id" value="1"/>
		<input type="hidden" name="comm_activity_on_user" id="comm_activity_on_user" value=""/>
		<input type="hidden" name="comm_i1" id="comm_i1" value="<?php echo $this->example[0]['id']; ?>"/>
		<input type="hidden" name="comm_i2" id="comm_i2" value=""/>
		<input type="hidden" name="comm_t1" id="comm_t1" value="Example"/>
		<input type="hidden" name="comm_t2" id="comm_t2" value="Comment"/>
	</form>
	<!--  end add vote on comments -->	
	
	<!--  start add vote on example_concept -->
	<form id="qe_vote_form" method="post" action="/votes/add?prefix=qe_">
		<input type="hidden" name="qe_obj_id" id="qe_obj_id" value=""/>
		<input type="hidden" name="qe_obj_type" id="qe_obj_type" value="4"/>
		<input type="hidden" name="qe_vote_value" id="qe_vote_value" value=""/>
		<input type="hidden" name="qe_activity_type_id" id="qe_activity_type_id" value="4"/>
		<input type="hidden" name="qe_activity_on_user" id="qe_activity_on_user" value=""/>
		<input type="hidden" name="qe_i1" id="qe_i1" value="<?php echo $this->example[0]['id']; ?>"/>
		<input type="hidden" name="qe_i2" id="qe_i2" value=""/>
		<input type="hidden" name="qe_t1" id="qe_t1" value="Example"/>
		<input type="hidden" name="qe_t2" id="qe_t2" value="ExampleConcept"/>
	</form>
	<!--  end add vote on example_concept -->
	
	
	<!--  start add example_concept -->
	<form id="qe_tag_form" method="post" action="/tags/add?prefix=qe_">
	<input type="hidden" name="qe_id" id="qe_id" value="<?php echo $this->example[0]['id']; ?>"/>
	<input type="hidden" name="concept_id" id="concept_id" value=""/>
	<input type="hidden" name="tag_type" id="tag_type" value="1"/> <?php // 1 for example, 2 for questions?>
	
<?php 
/**
 * we need new types of activity for this
 */
?>
<!-- 
		<input type="hidden" name="ex_activity_type_id" id="ex_activity_type_id" value=""/> 
		<input type="hidden" name="ex_activity_on_user" id="ex_activity_on_user" value=""/> 
	
		<input type="hidden" name="ex_i1" id="ex_i1" value="<?php //echo $this->example[0]['id']; ?>"/>
		<input type="hidden" name="ex_i2" id="ex_i2" value=""/>
		<input type="hidden" name="ex_t1" id="ex_t1" value="Example"/>
		<input type="hidden" name="ex_t2" id="ex_t2" value="ExampleConcept"/>
-->
	</form>
	<!--  end add example_concept -->
	<!-- </div> --> <!-- closes both video and image containers -->
<?php 

} // end single view
?>
<!--  
<div id="test-data">test-data</div>
 -->
 
</div>
<!-- /example-container -->

<?php 
//////////////////////////////////////////
/**
 * 
 * gets first level comments ids
 * @param unknown_type $id
 */
function getCommentsIds($id, $obj_type)
{
	$q = Doctrine_Query::create()
	->select('e.id')
	->from('Comment e')
	->where('e.obj_id = ? AND e.obj_type =? AND e.run_id = ?', array($id, $obj_type, $_SESSION['run_id']));
	 
	$result = $q->fetchArray();

	return $result;
}
 
function getConcepts($id)
{
	$q = Doctrine_Query::create()
	->select('e.id, e.example_id,  e.concept_id')
	->from('ExampleConcept e')
	->where('e.example_id = ? AND e.run_id = ?', array($id,$_SESSION['run_id']));
	 
	$result = $q->fetchArray();

	return $result;
}

function getExample($example_id)
{
	$q = Doctrine_Query::create()
	  ->from('Example e')
	  ->where('e.id = ?', $example_id);
	 
	$example = $q->fetchArray();
	
	//print_r($example);
	return $example;
}

function getQuestion($id)
{
	$q = Doctrine_Query::create()
	  ->from('Question e')
	  ->where('e.id = ?', $id);
	 
	$result = $q->fetchArray();
	
	//print_r($result);
	return $result;
}

function getUserName($author_id)
{
	$q = Doctrine_Query::create()
	  ->select('u.display_name')
	  ->from('User u')
	  ->where('u.id = ?', $author_id);
	 
	$user = $q->fetchArray();
	
	//print_r($user);
	return $user[0]['u.display_name'];
	
}

function countVotes($obj_id, $obj_type)
{
//	echo "<hr>obj_id: ". $obj_id;
//	echo "<hr>obj_type: ".$obj_type;
	// get all votes for this post: note that we can use SUM in SQL instead
	// ********************************************************************* 
    $q = Doctrine_Query::create()
	//->select ("v.id, v.vote_value, u.id, u.display_name") // use this if we want to show who and how someone voted
	->select ("v.id, v.vote_value")
	->from("Vote v")
	//->innerJoin("v.User u")
	->where('v.run_id = ? AND v.obj_id = ? AND v.obj_type = ?' , 
	array($_SESSION['run_id'],$obj_id, $obj_type)) 				
	->orderBy('v.id DESC');
	
	$votes = $q->fetchArray();

	$votesCount = array();
	$votesSumm = 0; $votesMinus = 0; $votesPlus = 0;
	
	foreach ($votes as $vote)
	{
		$votesSumm += $vote['vote_value'];
		
		if($vote['vote_value']==-1)
		{
			$votesMinus-= $vote['vote_value'];
		} else {
			$votesPlus+= $vote['vote_value'];
		}
		
	}
	$votesCount = array (
		"votesSumm" => $votesSumm,
		"votesMinus" => $votesMinus,
		"votesPlus" => $votesPlus
	);
	return $votesCount;
	// end get votes
	
} // end countVotes()

// don't need the author
function checkHasAssessment($author_id, $obj_id, $obj_type)
{
	/*
	echo "<hr>author_id: ".$author_id;
	echo "<br>sess: author_id: ".$_SESSION['author_id'];
	echo "<br>obj_id: ".$obj_id;
	echo "<br>obj_type: ".$obj_type;
	*/
	
	global $notAssessedItems;
	
	// checked ok!
	$q = Doctrine_Query::create()
	->select('a.id, a.mark')
	->from('Assessment a')
	->where('a.run_id = ? AND a.obj_id = ? AND a.obj_type = ?', 
		array($_SESSION['run_id'], $obj_id, $obj_type));
	 
	$assessment = $q->fetchArray();
	
	//echo "<br>";
	//print_r($assessment);
	
	if(count($assessment)==0)
	{
		// add this iterm to the assessment list
		$notAssessedItems .= "".$obj_id.",";
		//return "has no assessment";
		//echo "<hr>checkHasAssessment: ".$notAssessedItems;
		if($_SESSION['profile']=="TEACHER")
		{
			return renderAssessmentFormItem($obj_id);
		} else {
			return "";
		}
		
	} else {
		return '<div class="assessment-mark">'.$assessment[0]['mark'].'</div>';
		
	}
	
	//return $assessment;
}

function renderAssessmentFormItem($id)
{
	$assessmentForm = '
	<div class="assessment-item">
			<input type="radio" value="1" name="mark_'.$id.'">1  |
			<input type="radio" value="2" name="mark_'.$id.'">2  |
			<input type="radio" value="3" name="mark_'.$id.'">3  |
			<input type="radio" value="4" name="mark_'.$id.'">4   
			<input type="hidden" value="'.$id.'" name="obj_id_'.$id.'">
	</div>
	';
	return $assessmentForm;
}

function getCommentById($id,$prefix="")
{
	global $notAssessedItems;
	
	$prefix="comm_";
	
	$repliesHtml= ""; // stores all the threaded discussion html

	// get comment and user data
	$q = Doctrine_Query::create()
		->select ("c.*, u.display_name, u.id")
		->from("Comment c")
		->innerJoin("c.User u")
		->where('c.id = ? ', $id);
	
	$post = $q->fetchArray();

	$votesCount = countVotes($id,1); // look for votes only on obj_type = 1 comments
	
	// check if this is my comment
	if($_SESSION['author_id']==$post[0]['User']['id'])
	{
		$myCommentCss="my-comment";
		$isMyComment=true;
	} else {
		$myCommentCss="";
		$isMyComment=false;
	}
	
	$repliesHtml .= "
	<ul>";
	
	// add this post data
	//Id:'.$id.'
	$repliesHtml .='
	<li>
		<div class="post-item '.$myCommentCss.'">';
	
	// add/check assessment if is a teacher || this is my post
	//if($_SESSION['profile']=="TEACHER")
	if($_SESSION['profile']=="TEACHER" || $isMyComment)
	{
		
		$repliesHtml .=''.checkHasAssessment($post[0]['User']['id'], $id, 1); // obj_type = 1 comments in assessable
	}
	
	//$repliesHtml .='notAssessedItems: '.$notAssessedItems;
	
	// prevent autor from votting
	if($_SESSION['author_id']!=$post[0]['User']['id'])
	{
	// votes container 
	$repliesHtml .='
			<div class="votes-container" style="float:right;">
				<div id="'.$prefix.'vote-loading-'.$id.'"></div> 
				<div id="'.$prefix.'vote-minus-'.$id.'" class="vote-minus-plus">
					'.$votesCount['votesMinus'].'
				</div> 
				<div class="vote-icon">
					<a href="javascript:postVote(-1,'.$id.',1,'.$_SESSION['author_id'].',\''.$prefix.'\');"><img src="/images/icon_arrow_down.png" width="20px"></a>
				</div>
				<div id="'.$prefix.'vote-total-'.$id.'" class="vote-total">
					'.$votesCount['votesSumm'].'
				</div> 
				<div class="vote-icon">
					<a href="javascript:postVote(1,'.$id.',1,'.$_SESSION['author_id'].',\''.$prefix.'\');"><img src="/images/icon_arrow_up.png" width="20px"></a>
				</div>
				<div id="'.$prefix.'vote-plus-'.$id.'" class="vote-minus-plus">
					'.$votesCount['votesPlus'].'
				</div> 
			</div>';
	} // end if
	
	// comment content
	$repliesHtml .='<div id="comment' . $id  . '">				
			<div class="post-content">'
				.$post[0]['content'].'
			</div>
			</div>
			';
	
	// author name 			
	$repliesHtml .='
	        <div class="post-meta">
			  <div class="post-author">	
				<span>Posted by:</span> <a href="#">'.$post[0]['User']['display_name'].'</a>
			  </div>
			
			  <div class="post-reply">	
				<a href="javascript: postReply('.$id.','.$post[0]['User']['id'].')">[Reply]</a>
			  </div>
			</div>
		</div>
	</li>';
//*/


	//go recursive here: not the best approach 
	// we need a contract expand here 
			
// determine if the comment has replies
	$commentReplies = getCommentsIds($id, 1);
	$tot=0;
	$tot=count($commentReplies);
	//echo "<hr/>";
	//echo "<br/>Id:".$id;
	//echo "<br/>replies: ".count($commentReplies); 
	//print_r($commentReplies);
	
///*
	if($tot>0)
	{ 
		$repliesHtml .= "
	<li>
			<ul>";
		
		foreach ($commentReplies as $replies)
		{
			$repliesHtml .= '
				<li>'.getCommentById($replies['id']).'</li>';
		
			//$repliesHtml .= '<li>'.$replies['$id'].'</li>';
		}
		$repliesHtml .= "
			</ul>
	</li>";
	}
//*/

	// close main </ul>
			$repliesHtml .= "
</ul>";
	
	return  $repliesHtml;
	
} // end fnc

function analyzeTags($tags, $prefix="")
{
	$prefix = "qe_"; // same for voting on question_concept and example_concept 

	//get all Concepts in db for comparison: which ones are not added yet
	$q = Doctrine_Query::create()
		->select('e.id,  e.name')
		->from('Concept e')
		->where('e.run_id = ?', $_SESSION['run_id']);
	
	$theConcepts = $q->fetchArray();
	
	//$theConcepts=Doctrine::getTable("Concepts")->findAll(Doctrine::HYDRATE_ARRAY);
	
	//print_r($theConcepts);
	//print_r($tags);
	
	$currentConcepts = array(); // collects the concepts already associated to the example
	//$notIncludedConcepts = array();
	$theConceptsF = array(); // formats the concepts in db to same structure than current $currentConcepts

	//$PLACEWEB_CONFIG['fConcepts']
	
	$tagsHtml = "";
	$notIncludedConceptsHtml = "";
	
	$whoHasVoted = array();
	$conn=0;
	
	// adjust the concepts from db 
	foreach($theConcepts as $concept)
	{
		$theConceptsF[$concept['id']] = $concept['name'];
	}
	
	//print_r($theConceptsF);
	
	foreach ($tags as $tag)
	{
		/* 
		 * get votes data
		 */ 

			// collect tags for comparison 
			$currentConcepts[$tag['concept_id']] = $theConceptsF[$tag['concept_id']];
			
		
		//var_dump($tag);
		//echo "<br/>".$tag['conceptId'];
		
			$votesCount = countVotes($tag['id'],4); // look for votes for obj_type = 4 example_concept
		
		$tagsHtml .='
		<li>
			<div class="tag-name">'.$theConceptsF[$tag['concept_id']].'</div>
			<div class="votes-container">
				<div  id="'.$prefix.'vote-loading-'.$tag['id'].'"></div> 
				<div  id="'.$prefix.'vote-minus-'.$tag['id'].'" class="vote-minus-plus">
					'.$votesCount['votesMinus'].'
				</div> 
				<div class="vote-icon">
					<a href="javascript:postVote(-1,'.$tag['id'].',4,'.$_SESSION['author_id'].',\''.$prefix.'\');"><img src="/images/icon_arrow_down.png" width="20px"></a>
				</div>
				<div  id="'.$prefix.'vote-total-'.$tag['id'].'" class="vote-total">
					'.$votesCount['votesSumm'].'
				</div>
				<div class="vote-icon">
					<a href="javascript:postVote(1,'.$tag['id'].',4,'.$_SESSION['author_id'].',\''.$prefix.'\');"><img src="/images/icon_arrow_up.png" width="20px"></a>
				</div>
				<div  id="'.$prefix.'vote-plus-'.$tag['id'].'" class="vote-minus-plus">
					'.$votesCount['votesPlus'].'
				</div> 
			</div>
		</li>';
			
			$conn++;
	}
	
	$notIncludedConcepts = array_diff($theConceptsF, $currentConcepts);

	//print_r($currentConcepts);
	//print_r($notIncludedConcepts);
	
	$notIncludedConceptsHtml = "
	<li> &nbsp; 
	</li>
	";
	
	// not included tags
	foreach ($notIncludedConcepts as $diffTagId => $diffTagVal)
	{
		$notIncludedConceptsHtml .='
		<li>
			<div class="tag-name">'.$diffTagVal.'</div>
			<div class="tag-add"><a href="javascript:addTag(\''.$diffTagId.'\');">[Add]</a></div>
		</li>';
		
		//echo "<br/>".$diffTagId;
	} 
	
	return $tagsHtml.$notIncludedConceptsHtml;

} // end fnc

?>
