<?php
//print_r($_SESSION);
?>
<!DOCTYPE html>
<!--<?php 
echo $this->doctype() ?>-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

  <title>PLACE.web</title>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js"></script>
    
    <script type="text/javascript" src="/jquery/jqueryfileupload/jquery.iframe-transport.js"></script>
    <script type="text/javascript" src="/jquery/jqueryfileupload/jquery.fileupload.js"></script>
    <script type="text/javascript" src="/jquery/jqueryfileupload/jquery.fileupload-ui.js"></script>
    
    <script type="text/javascript" src="/jquery/jplayer/jquery.jplayer.min.js"></script>
    <script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js"></script>
    
    <link type="text/css" rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/smoothness/jquery-ui.css" />
    <link type="text/css" rel="stylesheet" href="/jquery/jqueryfileupload/jquery.fileupload-ui.css" />
    <link type="text/css" rel="stylesheet" href="/jquery/jplayer/themes/blue.monday/jplayer.blue.monday.css" />

	<script src="/js/basic.js" type="text/javascript" ></script>
	<link type="text/css" href="/css/styles.css" rel="stylesheet" />
<?php 
	//echo $this->headLink()->appendStylesheet('/css/global.css') 
?>
<?php 
	require(APPLICATION_PATH.'/layouts/include/'.'tinymce.head.inc.php');
?>


</head>
<body> 	
<div id="container">
	<?php 
	require(APPLICATION_PATH.'/layouts/include/'.'header.inc.php');
	?>
	<div id="main_content">
		<a name="content"></a>
	    <?php echo $this->layout()->content ?>
		    
		    
	</div><!-- /main_content --> 
		<?php 
			require(APPLICATION_PATH.'/layouts/include/'.'footer.inc.php');
		?>
</div><!-- /container -->

<div id="debugMode">

<?php

?>
</div>
</body>
</html>
