<?php

/**
 * ActivityTypesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityTypesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityTypesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivityTypes');
    }
}