<?php

/**
 * ActivityType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ActivityType extends BaseActivityType
{
    public static $VOTED_ON_COMMENT = 1;
    public static $VOTED_ON_ANSWER = 2;
    public static $VOTED_ON_ANSWER_CONCEPT = 3;
    public static $VOTED_ON_EXAMPLE_CONCEPT = 4;
    public static $COMMENTED_ON_COMMENT = 5;
    public static $COMMENTED_ON_ANSWER = 6;
    public static $COMMENTED_ON_EXAMPLE = 7;
    public static $ASSESSED_COMMENT = 8;
    public static $ASSESSED_EXAMPLE = 9;
    public static $ASSESSED_ANSWER = 10;
    public static $CREATED_EXAMPLE = 11;
    public static $CREATED_QUESTION = 12;
    public static $ANSWERED_QUESTION = 13;
    public static $VOTED_ON_QUESTION_CONCEPT = 14; // unused
    public static $VOTED_ON_EXAMPLE_QUESTION = 15; // unused
    public static $TAGGED_QUESTION_WITH_CONCEPT = 16;
    public static $TAGGED_EXAMPLE_WITH_CONCEPT = 17;
}