<?php

/**
 * AnswersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnswersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnswersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Answers');
    }
}