<?php

/**
 * AssessableTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssessableTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssessableTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Assessable');
    }
}