<?php

/**
 * AssessmentReviewsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssessmentReviewsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssessmentReviewsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssessmentReviews');
    }
}