<?php

/**
 * AssessmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssessmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssessmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Assessment');
    }
}