<?php

/**
 * CommentableTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommentableTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CommentableTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Commentable');
    }
}