<?php

/**
 * CommentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CommentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Comments');
    }
}