<?php

/**
 * ConceptTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConceptTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConceptTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Concept');
    }
}