<?php

/**
 * ConceptsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConceptsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConceptsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Concepts');
    }
}