<?php

/**
 * EloTemplateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EloTemplateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EloTemplateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EloTemplate');
    }
}