<?php

/**
 * ExamplesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExamplesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExamplesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Examples');
    }
}