<?php

/**
 * ExampleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExampleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExampleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Example');
    }
}