<?php

/**
 * ExampleConceptTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExampleConceptTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExampleConceptTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExampleConcept');
    }
}