<?php

/**
 * QuestionConceptTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuestionConceptTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuestionConceptTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('QuestionConcept');
    }
}