<?php

/**
 * ResolvedUserAlertTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResolvedUserAlertTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResolvedUserAlertTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ResolvedUserAlert');
    }
}