<?php

/**
 * ResolvedUserAlertsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResolvedUserAlertsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResolvedUserAlertsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ResolvedUserAlerts');
    }
}