<?php

/**
 * RunsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RunsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RunsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Runs');
    }
}