<?php

/**
 * RunTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RunTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RunTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Run');
    }
}