<?php

/**
 * SmartroomHwTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SmartroomHwTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SmartroomHwTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SmartroomHw');
    }
}