<?php

/**
 * VotableTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VotableTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VotableTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Votable');
    }
}